docker/httpd/apache2.conf
This block the requests to xmlrpc.php.
=> Deny access to xmlrpc.php

docker/httpd/Dockerfile
=> Whoops, wrong path

docker/httpd/apache2.conf
The "main" Varnish service now takes care of perimeter defense for us.
=> Don't <FilesMatch> to defend

docker/httpd/docker-entrypoint.sh
INF-3425
Add the logging CF-Connecting-IP header for apache.
=> Add CF-Connecting-IP header into the apache logs

docker/httpd/Dockerfile, docker/mgmt/Dockerfile, docker/wp-base/Dockerfile
As per today's conversation in the daily stand-up meeting:
- Add back php7.3-mbstring
- Also suppress some `apt install` duplication
=> Fix apt packages in image

docker/wp-base/Dockerfile
* Go back to ENV for ${PHP_VERSION}
* Add an explanatory comment
=> Looks like ARG isn't inherited through FROM

docker/wp-base/Dockerfile, docker/wp-base/install-plugins-and-themes.py
- Fix mis-named plugins
- Add mu-plugins and themes
Before:
-  `/wp/wp-content/plugins/wordpress.plugin.accred-vpsi`
- No mu-plugins or themes
After: https://termbin.com/1omr
=> More things in the image

docker/filebeat/Dockerfile, docker/filebeat/docker-entrypoint.sh
Add a filebeat container to ships web services logs to KELK stack
=> Add filebeat container for web services logs

README.md
As per https://docs.travis-ci.com/user/status-images/
=> Travis sticker for wp-ops

docker/wp-base/Dockerfile
This will simplify / speed up work when ventilating into a symlinked site.
=> Add wordpress-importer to image

ansible/roles/wordpress-instance/vars/symlink-vars.yml
Looks like this went through the cracks during #59.
=> Do symlink the "2010" plugins

docker/wp-base/Dockerfile
Ajout d'un nouveau package WPCLI avec une fonctionnalité propore à l'EPFL.
Un repo pour le package en question a été fait ici : https://github.com/epfl-idevelop/wp-cli/
=> Add new EPFL WPCLI package

ansible/roles/wordpress-instance/tasks/plugins.yml
Will also be installed on all sites when Ansible Tower comes into play
=> Coming Soon plug-in in image

ansible/roles/wordpress-openshift-namespace/templates/Jenkinsfile
Use translation of "build" instead
=> As per consensus in the team, "compilation" is the wrong terminology.

docker/filebeat/docker-entrypoint.sh
Add the new /call_logs path to read logs from
=> Add /call_logs path for filebeat

ansible/roles/wordpress-instance/tasks/plugins.yml, ansible/roles/wordpress-instance/vars/plugin-vars.yml
Same as #79 that I closed by mistake (by deleting the branch it was based upon)
=>  Add class-specific plugins into the image

docker/wp-base/install-plugins-and-themes.py
Fixes this morning's breakage, caused by #77
=> Don't rename muplugins

docker/httpd/docker-entrypoint.sh
Cette PR devra être mergée en même temps que les suivantes (qui sont toujours en WIP)
- https://github.com/epfl-idevelop/jahia2wp/pull/1025
- https://github.com/epfl-idevelop/jahia2wp/pull/1026
=> Update folder to fit new requirements

ansible/roles/wordpress-instance/tasks/plugins.yml
Just a one-line change for terminology, should have no effect.
=> Terminology fix in comments

ansible/roles/wordpress-instance/tasks/symlink.yml, ansible/roles/wordpress-instance/templates/symlinks-lib-tests.sh, ansible/roles/wordpress-instance/templates/symlinks-lib.sh
* introduce ensure_symlink
* introduce to_dotdots with unit test
=> Support the symlink scheme for multiple wordpress versions

docker/httpd/Dockerfile, docker/httpd/docker-entrypoint.sh, docker/httpd/dyn-vhost.conf
No functional change; this PR arose from a code explanation session.
=> Make dyn-vhost.conf a file of its own

docker/cleanup-call-logs/Dockerfile, docker/cleanup-call-logs/cleanup.sh
Add a docker image to rotate and cleanup the call logs.
=> Cleanup call logs

ansible/roles/wordpress-instance/tasks/main.yml, ansible/roles/wordpress-instance/vars/jahia2wp-vars.yml, ansible/roles/wordpress-instance/vars/main.yml, ansible/roles/wordpress-instance/vars/plugin-vars.yml
- Fix running `jahia2wp` in the first place
- Make sure that running it twice results in green Ansible
=> Run `jahia2wp shortcode-to-block` from within Ansible

ansible/roles/wordpress-instance/tasks/shortcode-to-block.yml
J'ai oublié de pushé un fichier !
=> Add forgotten file

ansible/roles/wordpress-instance/tasks/plugins.yml
Désactivation du plugin epfl-menus dans l'image.
=> Ensure epfl-menus is inactive

docker/httpd/Dockerfile, docker/httpd/msmtprc, docker/httpd/php.ini
This installs [msmtp](https://marlam.de/msmtp/) in the image and 
configures it for the EPFL environment.
=> [feature] Activate sendmail in httpd containers

ansible/roles/wordpress-instance/vars/symlink-vars.yml
En référence à https://github.com/epfl-idevelop/wp-ops/pull/140
=> Change symlink names for EPFL custom editor menu

Makefile
Sorry, didn't think to test this (as I was the one creating the depots)
=> [fix] Wrong paths

Makefile
- Fix bugs
- Add ability to set custom commit message
=> [improve] `make gitbackup`

ansible/roles/wordpress-instance/tasks/plugins.yml
=> Remove disable-wp-rest-api plugin

docker/wp-base/install-plugins-and-themes.py
Légère modification des conditions d'installation dans le script qui met les plugins dans l'image. Toujours pas compris comment ça fonctionnait avant.
=> Ensure all plugin are installed in image

ansible/requirements.yml, ansible/roles/wordpress-openshift-namespace/meta/main.yml
Pursuant to https://github.com/ansible/galaxy/issues/2266
=> [rename] epfl_idevelop → epfl_si

docker/wp-base/Dockerfile
Fixes the security problem highlighted in INC0329570
=> [security] Remove unused WordPress entry points

ansible/roles/awx-poc-vpsi/vars/main.yml, ansible/roles/wordpress-openshift-namespace/tasks/awx.yml, ansible/roles/wordpress-openshift-namespace/tasks/main.yml, ansible/roles/wordpress-openshift-namespace/templates/awx/awx-settings.py, ansible/roles/wordpress-openshift-namespace/templates/awx/nginx.conf, ansible/roles/wordpress-openshift-namespace/vars/awx-vars.yml
- Set OC objects for AWX
- Provide a personal nginx.conf for AWX to force the use of the port 8052 instead the default 80, as the 80 need the root permission
=> Set AWX to deploy at a specific version

ansible/inventory/wp-veritas/wp_veritas_inventory.py
As per the discussion today, we want to apply Ansible to these sites
(even though they are in a state of obsolescence)
=> [feature] `subdomains` is now a target for Ansible

ansible/roles/awx-instance/tasks/inventories.yml, ansible/roles/awx-instance/tasks/job-templates.yml, ansible/roles/awx-instance/tasks/main.yml, ansible/roles/awx-instance/templates/job-templates-create.py
- Create "Set up theme to sites" and "Align sites" job templates
- Reorganize tags a bit
=> First real-world AWX tasks (job templates)

ansible/wpsible
This leverages https://github.com/epfl-si/ansible.suitcase/commit/9e341868b2cc4e1c9103b738b7b69913f1cec7d9
=> [fix] Install `requests` into the pyenv

ansible/roles/wordpress-instance/tasks/main.yml, ansible/roles/wordpress-instance/tasks/serving-infrastructure.yml, ansible/roles/wordpress-instance/vars/main.yml, ansible/roles/wordpress-instance/vars/plugin-vars.yml, ansible/roles/wordpress-openshift-namespace/tasks/mgmt.yml, ansible/vars/wordpress-vars.yml
Sorry for kicking it in the first place
=> [fix] Restore WP_VERSION variable

docker/mgmt/new-wp-site.sh
- Use HTTP/S URL for the site when running under Kubernetes
- Use `--extra-php` like jahia2wp did
=> [fix] Misc fixes to new-wp-site

docker/mgmt/Dockerfile
=> [feature] tmux

Makefile
- Backup routes and deploymentconfigs
- Pull before push
=> [feature] Improve Keybase backup of k8s objects

ansible/roles/wordpress-instance/tasks/site-metadata.yml
=> [fix] escape blogname and blogdescription

ansible/roles/wordpress-instance/action_plugins/wordpress_polylang_language.py
=> [fix] Set english locales to en_US

ansible/wpsible
=> [feature] Ask user to login to openshift

ansible/roles/wordpress-instance/tasks/main.yml, ansible/roles/wordpress-instance/tasks/plugins.yml
Bring the "BEGIN EPFL-Intranet" block under Ansible's control (and rename it)
Fixes #275
=> [fix] EPFL-Intranet htaccess

ansible/roles/wordpress-instance/tasks/main.yml
... in order to usefully link to it from Confluence.
- Explain the parallelism model, the tags, and the `when:` clauses
- Touch base on `wp_destructive`
=> [doc] Document `tasks/main.yml`

ansible/roles/wordpress-instance/tasks/reports.yml, ansible/roles/wordpress-instance/vars/reports-vars.yml
This is just the tail end of #290 that got delayed during a GitHub-side outage.
=> Ansible reports - Add destination file as a parameter

ansible/roles/wordpress-instance/filter_plugins/paths.py
=> [forgot] to `git add` this file

docker/mgmt/Dockerfile
=> [add] lnav to the mgmt image

ansible/roles/wordpress-instance/tasks/configure.yml, ansible/roles/wordpress-instance/tasks/main.yml
Also, fix a few loose ends in #301
=> [fix] Repair red when trying to invalidate NFS caches

ansible/roles/wordpress-instance/tasks/plugins.yml, ansible/vars/wordpress-vars.yml
And unlock the version of TinyMceget the latest version of tinymce
=> Default to 5 4 WP; Unlock the TinyMce plugin version

ansible/ansible.cfg, ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py, ansible/roles/wordpress-instance/action_plugins/wordpress_facts.py, ansible/roles/wordpress-instance/tasks/reports.yml, ansible/roles/wordpress-instance/vars/main.yml
Quelques essais d'amélioration du temps d'exécution
=> Process time optimizations

.travis.yml, ansible/roles/wordpress-instance/tasks/plugins.yml, ansible/roles/wordpress-instance/vars/plugin-vars.yml, docker/wp-base/Dockerfile
This PR aims to use symling for wpforms and wpforms-epfl-payonline.
=> [feature] symlink wpforms

ansible/roles/awx-instance/tasks/k8s-builds.yml
Put forth the required infrastructure to patch ansible and ansible-runner (but don't make use of it yet)
=> [fix] Apply (no) patches to the awx-runner images

ansible/roles/awx-instance/tasks/k8s-builds.yml, ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner, docker/mgmt/Dockerfile
This is so that we can performs backups onto EPFL's Scality infrastructure.
=> [feature] Add restic binary to the mgmt and awx-runner images

.gitignore
This directory is managed by the Makefile.
=> [ignore] k8s-backup

ansible/roles/wordpress-openshift-namespace/tasks/main.yml, ansible/roles/wordpress-openshift-namespace/tasks/varnish.yml, ansible/roles/wordpress-openshift-namespace/vars/varnish-vars.yml
- Constant pod names (regardless of prod vs. test)
- Create Kubernetes objects from Ansible
=> [feature] Run Varnish from Ansible

ansible/inventory/wordpress-instances.py, ansible/roles/awx-instance/tasks/inventories.yml
- Additional groups
- Clean up old hosts that are no longer part of the inventory
=> [feature] AWX inventory improvements

docker/httpd/global-error/403-template.php
Add new EPFL favicon to 403-template.php
=> change to new EPFL favicon

ansible/roles/wordpress-instance/tasks/plugins.yml
Following https://github.com/epfl-si/wp-ops/pull/341
=> Fix forgotten deletion of a wp-destructive assertion

ansible/roles/awx-instance/tasks/job-templates.yml
This PR provide an ansiblified job template for the backups and a scheduler (right now set at 03:03:03 and limited to prod_subdomains_lite).
=> [feature] backup job template

ansible/roles/awx-instance/tasks/job-templates.yml, ansible/roles/wordpress-instance/tasks/backup.yml
- Backup all wordpresses exclude sandbox (archive sites)
- Use relatif path for restic backups
=> [Fix] Backup all wordpresses exclude sandbox (archive sites)

ansible/roles/wordpress-instance/vars/plugin-vars.yml
=> Set ewww debugger to off

ansible/roles/wordpress-instance/vars/main.yml
=> [fix] Add trailing slash of site URL

ansible/roles/awx-instance/tasks/k8s-builds.yml, ansible/roles/awx-instance/tasks/k8s.yml, ansible/roles/awx-instance/tasks/main.yml, ansible/roles/awx-instance/templates/awx-settings.py, ansible/roles/awx-instance/vars/k8s-vars.yml
- Upgrade AWX to version 15.0.1
- Fix Kubernetes `StatefulSet` layout; starting at version 13, the `awx-web` and `awx-task` containers share the same image
- Patch two (!) critical bugs in said image that only appear when using Kubernetes-based elastic container groups (hypothesis: EPFL is the ony team using this feature worldwide at the moment)
- Drop Memcache
=> [feature] AWX version 15

ansible/roles/wordpress-instance/tasks/plugins.yml
See https://wordpress.org/plugins/find-my-blocks/
=> [feature] manage new plugin 'Find my blocks'

ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner
=> [feature] Mitogen in wp-ansible-runner

ansible/roles/wordpress-openshift-namespace/tasks/images.yml, ansible/vars/image-vars.yml
This makes the two images identical.
=> [refactor] Move USER stanza from cronjob to mgmt

ansible/ansible.cfg, ansible/wpsible
As a follow-up to #348:
- Have the suitcase install Mitogen
- Change ansible.cfg to make use of it
=> [feature] Mitogen also in operator's wpsible

ansible/ansible.cfg, ansible/playbooks/wordpress-main.yml, ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner
Works around  https://github.com/dw/mitogen/issues/599
=> [feature] mitogen strategy only for wordpress instance role

ansible/roles/wordpress-instance/tasks/main.yml, ansible/roles/wordpress-instance/tasks/plugins.yml, ansible/roles/wordpress-instance/vars/plugin-vars.yml
Le but de cette PR est de pouvoir avoir le nouveau plugin epfl-coming-soon dans l'image pour ensuite faire des tests pour une autre PR pour son installation, son activation et l'armé ou le désarmé.
=> [feature] add plugin epfl-coming-soon

ansible/inventory/wordpress-instances.py
While pair-programming with @GregLeBarbar I was about to issue a more substantial PR, but it just so happens that none is needed at this time.
=> [comment] Inventory works on AWX in the wwp-infra namespace

ansible/roles/wordpress-instance/tasks/plugins.yml, ansible/roles/wordpress-instance/vars/plugin-vars.yml
Tests sur un site : 
- avec le plugin epfl-coming-soon armé
- avec le plugin epfl-coming-soon désarmé 
- nouvellement créé
=> [feature] coming soon is dead

ansible/playbooks/wordpress-main.yml
Allows you to choose Ansible's strategy when running the playbook
=> Make strategy a variable

docker/httpd/global-error/403-template.php
- New Elements version from web2018 production servers
- Fix footer position
- Update year
=> Update 403 "Access denied" page 

docker/disk-usage-statistics/index.ts, docker/disk-usage-statistics/package-lock.json, docker/disk-usage-statistics/package.json
- `npm i --save-dev @types/commander`
- Make `docker/disk-usage-statistics/index.ts` TypeScript-perfect
-
=> [fix] Some TypeScript

ansible/roles/wordpress-openshift-namespace/tasks/varnish.yml, ansible/roles/wordpress-openshift-namespace/templates/varnishkafka.conf
This add configmaps and options between wwp-test and wwp environement.
=> [feature] varnish cache

ansible/roles/wordpress-instance/tasks/create.yml, docker/mgmt/new-wp-site.sh
May fix https://github.com/epfl-si/wp-ops/issues/424
Please test before merge
=> Fix site title being 'htdoc' when creating subdomains-lite sites

ansible/inventory/wordpress-instances.py, ansible/roles/wordpress-instance/defaults/main/command-line-vars.yml, ansible/roles/wordpress-instance/tasks/plugins.yml, docker/mgmt/Dockerfile, docker/mgmt/jahia2wp.sh
See also https://github.com/epfl-si/wp-dev/pull/61
- Remove jahia2wp from the mgmt image
- Delete the last comments, wrapper scripts etc. refering to it
=> [remove] jahia2wp

ansible/README.md, ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner
- Fix yet another reference to operator's checked out branch
- Update misleading doc
-
=> [fix] wp-ansible-runner not building anymore

ansible/roles/wordpress-instance/tasks/create.yml, ansible/roles/wordpress-instance/tasks/site-metadata.yml
Some quoting gymnastics to deal with quotes in site's tagline.
This fixes #445.
=> [fix] Tagline quotes

ansible/roles/wordpress-openshift-namespace/tasks/images.yml, ansible/roles/wordpress-openshift-namespace/vars/monitoring-vars.yml, ansible/roles/wordpress-openshift-namespace/vars/secrets-wwp.yml
- Nevergreen fixed by picking a fixed salt for hashed passwords
- Defective tag `-t images.promote`
=> [fix] several Ansible gotchas

ansible/roles/awx-instance/tasks/auth.yml, ansible/roles/wordpress-instance/README.md, ansible/roles/wordpress-instance/lookup_plugins/env_secrets.py, ansible/roles/wordpress-instance/lookup_plugins/wpveritas.py, docker/disk-usage-statistics/package.json, docker/jenkins/Dockerfile, docker/monitoring-wpprobe/package.json
=> [fix] ISAS, ISAS, ISAS 🎶🎵

ansible/roles/wordpress-openshift-namespace/README.md
#479, “more of the same” edition
=> [fix] IDEV → ISAS

docker/mgmt/Dockerfile
This is part of the hunt triggered by https://go.epfl.ch/INC0468760
=> [feature] Add `ag` binary to the mgmt image

ansible/roles/wordpress-instance/tasks/main.yml, ansible/roles/wordpress-instance/tasks/plugins.yml, ansible/roles/wordpress-instance/vars/plugin-vars.yml
This add the add-on Surveys and Polls to WPForms, linked to the category "Surveys" on wp-veritas
=> [feature] WPForms Surveys & Polls

ansible/roles/wordpress-instance/tasks/plugins.yml
=> [feature] WPForms with survey versions 1.6 & 1.7

.gitignore, README.md, update_contributor.sh
This automatize the part of the README where the contributors are listed.
=> [feature] script that update the contributor's trombinoscope

ansible/roles/wordpress-openshift-namespace/tasks/continuous-integration.yml, docker/jenkins/epfl-plugins.txt
... And make `wpsible -t ci.rebuild` work.
=> [fix] Bring back Jenkins' “pipeline stage view”

ansible/roles/wordpress-openshift-namespace/tasks/k8s-objects-httpd.yml, docker/httpd/docker-entrypoint.sh
Please see https://github.com/epfl-si/wp-dev/pull/68
=> [fix] smtp secret

docker/jenkins/epfl-plugins.txt
𝄞 Hey, I don't know much about Jenkins and its plugins, and this is crazy
🎵 But I noticed that the ones that are failing are the ones without a version pin
🎶 So fix the build maybe? 🎻
=> [fix] the Travis build

ansible/roles/wordpress-openshift-namespace/vars/web2010-vars.yml
Following https://github.com/epfl-si/web2010/pull/97
=> Update base images for web2010

docker/wp-base/Dockerfile
Add the [bash-completion](https://github.com/scop/bash-completion)  package form more comfort.
=> [feature] bash-completion

ansible/roles/wordpress-instance/tasks/main.yml, ansible/roles/wordpress-instance/tasks/plugins.yml, ansible/roles/wordpress-instance/vars/plugin-vars.yml
This plugin show the diploma verification form to check his validity with a ISA Web Service call.
=> Add diploma verification plugin

ansible/roles/wordpress-instance/tasks/main.yml, ansible/roles/wordpress-instance/tasks/plugins.yml, ansible/roles/wordpress-instance/vars/plugin-vars.yml
Add partner universities plugin
=> [Feature] new partner universities plugin

ansible/inventory/prod/group_vars/openshift_namespaces_prod, ansible/inventory/wordpress-instances.py, ansible/roles/wordpress-instance/filter_plugins/routes.py, ansible/roles/wordpress-instance/vars/routes-vars.yml, ansible/roles/wordpress-openshift-namespace/templates/prometheus-menu-service-discovery.py
Remove config for unmanged sites
=> refactor remove unmanaged conf

ansible/roles/wordpress-openshift-namespace/tasks/main.yml, ansible/roles/wordpress-openshift-namespace/tasks/report-uri.yml, ansible/roles/wordpress-openshift-namespace/vars/report-uri-vars.yml
-- See https://github.com/epfl-si/report-uri
=> Include deployment of CSP Report URI

docker/wp-base/Dockerfile
Automation of new elements styleguide into theme
=> [Feature] build and install elements from source

docker/wp-base/Dockerfile
=> Revert "[fix] build on M1 processors"

ansible/roles/wordpress-openshift-namespace/tasks/monitoring.yml, ansible/roles/wordpress-openshift-namespace/templates/prometheus-config.yml, ansible/roles/wordpress-openshift-namespace/vars/monitoring-vars.yml
- add menu-api-siblings container into monitoring
=> [feature] add metrics for menu-api-siblings

ansible/wpsible
Sorry to all that have a user `$USER` that doesn't match their EPFL  username (hehe).
=> [fix] `oc login` now specify server

docker/nginx/Dockerfile, docker/nginx/php.ini
=> [fix] WPN-79

kopf-operator/wpn-kopf.py
Fixes [WPN-112](https://erpdev.atlassian.net/browse/WPN-112)
[WPN-112]: https://erpdev.atlassian.net/browse/WPN-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix] Shell injection attack

ansible/inventory/rke2/hosts-test.yml
I showed him the ropes, and told him not to break anything. (He made his own namepace for himself.)
=> [feature] Grant access to Laurent Indermühle

ansible/roles/rke2-cluster/meta/main.yml, ansible/roles/rke2-cluster/tasks/main.yml, ansible/roles/rke2-cluster/tasks/plugins.yml, ansible/roles/rke2-cluster/vars/rke2-cluster-vars.yml, test/wpn-sites.js
Create kind secret for plugins
=> [feature] WPN-97 gestion des plugins

docker/wp-base/Dockerfile, docker/wp-base/install-wordpress.sh
Delete from image the following plugins:
- svg-support
- wp-plugin-epfl-emploi
Upgrade versions:
- find-my-blocks : 3.5.5 --> 3.5.6
- wp-media-folder : 5.3.21 --> 5.9.13
Get modified plugins from `feature/upgradePHPAndWordpressVersion` branch.
=> [feature] Update plugins on image

ansible/roles/wordpress-namespace/tasks/nginx.yml, docker/wordpress-php/www.conf.overrides
- Golang thingie by https://github.com/hipages/php-fpm_exporter
- `pm.status_listen` and `pm.status_path` configuration options documented here: https://www.php.net/manual/en/install.fpm.configuration.php#pm.status-path
=> [feature] php-fpm exporter sidecar container

docker/wordpress-php/www.conf.overrides
This is an attempt to resolve the two outages of yesterday night and this morning.
=> [fix] Pump FPM workers way up

ansible/roles/wordpress-namespace/tasks/nginx.yml, docker/wordpress-php/nginx-entrypoint.php, docker/wp-base/install-wordpress.sh
This may¹ fix the lack of a Polylang 302 response at the root of the site; also known as (the tail end of) https://go.epfl.ch/WPN-248
¹  ... or it may not? But I can't see what this could break #famouslastwords
=> [fix] Tell PHP we are on HTTP/S

ansible/roles/wordpress-namespace/tasks/menu-api.yml, ansible/roles/wordpress-namespace/vars/menu-api-vars.yml
Also delete some dead code concerning menu-api
=> [feature] Add REQUEST_TIMEOUT environment variable

ansible/roles/wordpress-namespace/templates/grafana/Nginx.json
Jira : https://erpdev.atlassian.net/browse/WPN-325
Based on https://grafana.com/grafana/dashboards/10223-nginx-lua/.
=> [feature](WPN-325) Grafana Dashboard for Nginx

ansible/roles/wordpress-namespace/tasks/menu-api.yml
- Add PodMonitor for menu-api
- change cpu from 100m to 500m
=> [feature] add menu-api monitoring

ansible/roles/wordpress-namespace/tasks/monitoring.yml
https://erpdev.atlassian.net/browse/WPN-329
> Alert on more than 1 MariaDB pod restart within 15 minutes
=> [feature](WPN-329) Add alerts on too many MariaDB restarts

ansible/roles/wordpress-namespace/tasks/monitoring.yml, ansible/roles/wordpress-namespace/templates/grafana/MenuAPI.json
- Alerts:
1. too many restarts
2. slow requests
3. the count of menu-api pods mismatch the number defined in the deployment
- Dashbaords:
1. latency dashboards
2. errors/requests dashboards
=> [feature] Menu api dashboard grafana and alerts

ansible/roles/wordpress-namespace/tasks/menu-api.yml
- make the base url as a variable depending on the environment
=> [fix ]base url

ansible/roles/wordpress-namespace/tasks/main.yml, ansible/roles/wordpress-namespace/tasks/report-uri.yml, ansible/roles/wordpress-namespace/vars/report-uri-vars.yml
-- Linked to https://github.com/epfl-si/report-uri/pull/7
=> [feature] Migrate report-uri to OpenShift 4

ansible/roles/wordpress-namespace/vars/image-vars.yml, docker/wp-base/install-wordpress.sh
Fixes [WPN-336](https://erpdev.atlassian.net/browse/WPN-336)
We might need to do some clicking on the “Hide URL language information etc etc.”, though.
[WPN-336]: https://erpdev.atlassian.net/browse/WPN-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [kludge] Twist Polylang's arm into doing redirects at the home page

docker/apache-redirector/httpd.conf
Mix our previous version with input of [SO](https://stackoverflow.com/a/43931457/960623).
=> [feature] JSON log format

docker/wordpress-nginx/nginx.tmpl
https://erpdev.atlassian.net/browse/WPN-391
=> [feature] Configure ngx_http_realip_module (NGINX module) to log real client IPs

ansible/roles/wordpress-namespace/tasks/wp-cron.yml, docker/wp-cron/wordpresses.py
WP-cron patch all CRs with activate plugins
=> [feature] Patch status with plugins

ansible/roles/wordpress-namespace/tasks/menu-api.yml
According to [this analysis](https://epflch-my.sharepoint.com/:x:/r/personal/quentin_vasseur_epfl_ch/_layouts/15/Doc.aspx?sourcedoc=%7B83506CAE-F525-4FB5-B07C-3B300AD4CFF4%7D&file=Combined.xlsx&nav=MTVfe0RFQzIzN0QxLTI2ODAtNDIyOC1BRjFGLTkxNDA5OTdBMThEMn0&action=default&mobileredirect=true ), decrease to 160m the request CPU
=> [fix] Decrease CPU request on menu-api

ansible/roles/wordpress-namespace/tasks/nginx.yml
Based on the last 30 days' usage:
=> [enhancement] Optimize CPU requests resources for nginx

docker/wp-base/Dockerfile
Near as I can tell, nothing sets `ELEMENTS_GIT_REPOSITORY` and therefore this `RUN` stanza has no effect.
=> [deadcode] Building `epfl-elements` from source

docker/wordpress-nginx/nginx.tmpl, docker/wp-base/Dockerfile
=> [unscaffold] that one last symlink

docker/wordpress-nginx/nginx.tmpl, docker/wordpress-php/nginx-entrypoint.php, docker/wp-base/Dockerfile
This is the Web integration for #697, complete with [proper](https://www.rfc-editor.org/rfc/rfc9512.html) `application/yaml` MIME type.
=> [feature] Serve (S)BOM at the root of each site, as YAML
