docker/httpd/docker-entrypoint.sh

Method and apparatus from
https://saz.sh/2010/12/02/insert-php-variables-into-apache-access-log/
- PHP changes to follow in the other repository.

Allow for performance logging to be done from inside Apache / PHP

---

docker/httpd/Dockerfile
docker/httpd/php.ini

As per yesterday's strace(1)-based examination, this is a candidate
for boosting performance by reducing the number of round trips to the
NAS.

Tune up the realpath cache

---

docker/mgmt/Dockerfile

Fix de l'erreur qui est apparue lors du build de l'image.
> WARNING: The following packages cannot be authenticated!
php7.1-common php7.1-json php7.1-opcache php7.1-readline php7.1-cli
libapache2-mod-php7.1 libgd3 libzip5 php7.1 php7.1-curl php7.1-gd
php7.1-ldap php7.1-mysql php7.1-xml php7.1-zip
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
Removing intermediate container 9335932b4735
error: build error: The command '/bin/sh -c apt-get -y install nodejs     php7.1     php7.1-gd     php7.1-cli     php7.1-curl     php7.1-ldap     php7.1-mysql     php7.1-xml     php7.1-zip   &&     apt-get -y autoremove &&     apt-get clean' returned a non-zero code: 100

Fix GPG error

---

docker/httpd/docker-entrypoint.sh
docker/httpd/ports.conf

Allow apache to handle requests for web services metrics.
A new document root with a `.htaccess` file must also be created in the file tree. For the `httpd-lchaboudez` pod :
```
mkdir -p /srv/lchaboudez/lchaboudez-metrics/htdocs
```
The `.htaccess`file :
```
RewriteEngine On
RewriteRule ^(.*)$ http://localhost:8080/$1 [P]
RequestHeader set Host env-lc-os-exopge.epfl.ch
```

Add support for web services metrics

---

docker/httpd/docker-entrypoint.sh

Change the custom log format in order to be able to log the X-EPFL-Trace-Id http header added by the A10.

Add X-EPFL-Trace-ID header into the apache logs

---

docker/httpd/403/403.php

Si on a l'information de l'adresse IP originale du client (champ ajouté dans `$_SERVER` par CloudFlare), on utilise cette valeur au lieu de celle contenue dans `REMOTE_ADDR` car cette dernière contient du coup une IP CloudFlare.

Use true client IP if behind CloudFlare when 403 error

---

docker/httpd/Dockerfile

Ajout du packag PHP "mbstring" afin de pouvoir avoir les fonctions mb_* pour les encodages. Celles-ci sont typiquement utilisées au sein de https://github.com/epfl-idevelop/jahia2wp/pull/942 et https://github.com/epfl-idevelop/jahia2wp/pull/943

Add PHP mbstring to have mb_* functions

---

docker/httpd/docker-entrypoint.sh

Modification qui n'avait pas été "revert" depuis décembre 2018 car on est finalement partis dans une autre direction et là, ça ne fait que remplir le filesystem avec les logs.
**POST REDEPLOIEMENT DE L'IMAGE**
- Supprimer les fichiers `/srv/www/logs/perf_log*` sur le NAS

Remove PHP perf log file

---

ansible/roles/wordpress-instance/tasks/update.yml

epfl and epfl-light setted a new folder structure -> https://github.com/epfl-idevelop/wp-theme-2018/pull/195

Change the path for new wp-theme structure

---

docker/httpd/docker-entrypoint.sh

Sur OpenShift, les logs des appels aux webservices sont mis dans un dossier de type "emptydir" (`/webservices/logs`) et ce dossier n'existe pas par défaut quand on fait tourner l'image "httpd" localement.
Ajout du nécessaire pour créer le dossier s'il n'existe pas afin que les logs puissent y être écrits.

Create dir for web service call log

---

docker/wp-base/Dockerfile
docker/wp-base/install-plugins-and-themes.py
docker/wp-base/install-plugins.py

In order to not reinvent the infrastructure to download subdirectories of GitHub depots (useful e.g. for  installing the wp-theme-2018 in its new directory layout), we open up the use cases for the `install-plugins.py` script.

Ability to use the install-plugins.py script manually

---

docker/wp-base/Dockerfile

- Fix build broken by rename
- Ensure that version 4.9.x of WordPress is the one we embed

No wordpress 5 for now

---

docker/httpd/403/403-inside.php
docker/httpd/403/403.php

Ajout d'une page d'erreur pour afficher un message différent dans le cas d'une tentative d'accès non-autorisée à la partie "visiteur" d'un site Inside.
Une PR a aussi été faite pour modifier le plugin "accred" afin qu'il puisse rediriger sur cette nouvelle page : https://github.com/epfl-sti/wordpress.plugin.accred/pull/11
Pour le moment, dans le cas d'un accès non autorisé à la partie visiteur d'un site inside, c'est le message d'erreur générique d'accès à la partie admin qui est affiché, à savoir:
Cette PR permet d'afficher un message différent (qui peut être amélioré si besoin):

Add inside website error page

---

ansible/inventory/prod/group_vars/openshift-namespaces-prod
ansible/inventory/test/group_vars/openshift-namespaces-dev
ansible/roles/wordpress-openshift-namespace/tasks/images.yml
ansible/roles/wordpress-openshift-namespace/vars/image-vars.yml

Now that #40 is merged, and we don't build in production anymore, the
branch to build images is just `master`.
Note: the change has already been pushed to the wwp-test namespace (try `oc edit bc/mgmt`, notice the lack of `ref:`)

Remove the `wp_ops_git_branch` variable

---

docker/wp-base/Dockerfile
docker/wp-base/install-plugins-and-themes.py

The reason epfl-idevelop/jahia2wp has a
data/plugins/generic/polylang/polylang.zip stuck in the past is so
that things work when importing a multilingual site converted from
Jahia. Since 1) we are no longer going to do that and 2) the version
of Polylang in /wp/ has no impact whatsoever on the jahia2wp Python
script, we want to override config-lot1.yml for that one plug-in.
- Make install-plugins-and-themes.py executable
- Invoke it once more in the Dockerfile for Polylang
- Make it so "wordpress.org/plugins" is a synonym to "web" as a source
URL for a plug-in

Update Docker image's Polylang to latest version

---

docker/mgmt/docker-entrypoint.sh

Déplacement de la commande qui démarre le deamon SSH dans `mgmt` car sinon, impossible de faire du debug en mode développement.

Ensure SSH daemon starts, even if in dev mode

---

ansible/inventory/test/group_vars/charte-wordpresses
ansible/inventory/test/group_vars/migration-int-wordpresses

This makes wpsible work in dev also for people who don't have a
suitable setting in their ~/.ssh/config

Set `ansible_user` in test inventory

---

ansible/inventory/prod/wordpress-instances
ansible/inventory/test/group_vars/charte-wordpresses
ansible/inventory/test/group_vars/migration-int-wordpresses
ansible/inventory/test/wordpress-instances
ansible/playbooks/wordpress-main.yml
ansible/roles/wordpress-instance/defaults/main/report-vars.yml
ansible/roles/wordpress-instance/filter_plugins/wp_inventory_csv_report.py
ansible/roles/wordpress-instance/filter_plugins/wp_inventory_csv_reports.py
ansible/roles/wordpress-instance/tasks/facts.yml
ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/setup.yml
ansible/roles/wordpress-instance/vars/main.yml
ansible/wpsible

We can now say
```
./wp-ops/ansible/wpsible --prod -t facts,reportcsv
```
and get a report of all active plug-ins and their versions in `report.csv`
The fact collection (`-t facts` part) uses Ansible facts “the right way”, and caches them by default (no need to tweak your `~/.ansible.cfg`). New facts defined this way include `wp_is_installed`, `wp_is_symlinked` and `wp_plugin_list`.
[Example of a report generated using this data set](https://docs.google.com/spreadsheets/d/1bw5q1rEnmuSe3YV3lCedjznKFhMkA07yEQCTtJYdVDE)

Inventory report with Ansible with plug-in versions

---

docker/wp-base/Dockerfile

Right now, symlinked sites (e.g. `www-ventil2`) have a broken symlink
as their `wp-content/mu-plugins/index.php`.

Give /wp/wp-content/mu-plugins a defensive index.php too

---

ansible/roles/wordpress-instance/defaults/main/report-vars.yml
ansible/roles/wordpress-instance/filter_plugins/wp_inventory_csv_reports.py
ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/symlink.yml
ansible/roles/wordpress-instance/vars/symlink-vars.yml

- Produce a mu-plugin CSV report along with the plugin CSV report
- When a site is symlinked, be sure to get rid of its `mu-plugins/EPFL_enable_updates_automatic.php`
- Upon reviewing the data, we found that `EPFL_google_analytics_hook.php` is used exclusively in groups `prod-inside`, `prod-www` and `prod-labs` (in particular, not in `prod-subdomains`). Enforce that at `wpsible -t symlink` time

Mu-plugins improvements (reporting, symlinking discipline)

---

docker/wp-base/Dockerfile
docker/wp-base/install-plugins-and-themes.py

Analysis of the ground truth in production reveals that
- this plugin is the single most used plugin that is currently *not*
part of the image;
- it is extremely well curated, as all version numbers for this plugin
are the same in production.

Put "epfl-infoscience" and the "2010" plug-ins into the Docker images

---

ansible/playbooks/wordpress-main.yml
ansible/roles/wordpress-instance/tasks/configure.yml
ansible/roles/wordpress-instance/tasks/symlink.yml
ansible/roles/wordpress-instance/templates/maintenance-lib.sh
ansible/roles/wordpress-instance/templates/symlinks-lib.sh
docker/httpd/php.ini

- Back up / restore .htaccess instead of editing it (suggested by @LuluTchab)
- Do the symlink dance in one shell script
- Disable realpath_cache, lest “unsymlink” basically have no effect

Misc. fixes and improvements from the aftermath of OUT0001470

---

ansible/roles/wordpress-instance/action_plugins/wordpress_option.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/action_plugins/wordpress_theme.py
ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/tasks/themes.yml
ansible/roles/wordpress-instance/vars/accred-vars.yml
ansible/roles/wordpress-instance/vars/main.yml
ansible/roles/wordpress-instance/vars/plugin-vars.yml
ansible/roles/wordpress-instance/vars/theme-vars.yml
docker/wp-base/Dockerfile
docker/wp-base/install-plugins-and-themes.py

This is the first step towards moving the ground truth about plugins, themes and configuration options from [jahia2wp](https://github.com/epfl-idevelop/jahia2wp) to wp-ops.
- Add infrastructure under `ansible/` to manage plugins, themes and WP options (stubbed out for now)
- Translate `config-lot1.yml` from both jahia2wp branches (`release` and `release2018`) into Ansible
- `install-plugins-and-themes.py` now parses the YAML out of said Ansible state, rather than the one in jahia2wp
- Put up temporary warning at the top of  `plugins.yml` that explains that that configuration now exists in duplicate

Plugin and theme state in Ansible

---

ansible/roles/wordpress-openshift-namespace/templates/Jenkinsfile

[We recently had a rash of red Jenkins builds](https://jenkins-wwp-test.epfl.ch/job/wwp-test/job/wwp-test-httpd-jenkins-dev/) caused by Jenkins attempting to deploy `dc/httpd-int`, whereas that DeploymentConfig automatically redeploys itself whenever we build a new `httpd` image in `wwp-test`.
- Watch the DeploymentConfig instead of causing it, based the sample code in https://github.com/openshift/jenkins-client-plugin#looking-to-verify-a-deployment-or-service-we-can-still-do-that 
- `echo` a brief explanation of what we are waiting for once per deployment

Bugfix: Jenkins said "deployment already in progress"

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Following a typo, the content of  /wp/wp-content/plugins/cache-control is bogus in the image (contains a copy of the epfl-accred plugin). Fix it

Emergency fix - Content of /wp/wp-content/plugins/cache-control is bogus

---

ansible/inventory/test/wordpress-instances

This rids us of a spew of red errors (introduced in #69) every time we
run anything.

Don't walk /srv/lvenries or /srv/jenkins

---

.travis.yml
docker/wp-base/install-plugins-and-themes.py

Change plumbing so that the Ansible changes in wp-ops are visible to the Travis build.
- New flag `--manifest-url` to `install-plugins-and-themes.py`
- Use it from `.travis.yml` if `$TRAVIS_BRANCH$` is set

Build from feature branch with Travis

---

ansible/wpsible

I modified the script so that it tests the validated Keybase folder instead of just testing if the Keybase application is installed!

Check that /keybase exists (rather than the keybase command-line tool)

---

ansible/roles/wordpress-instance/tasks/plugins.yml
docker/wp-base/Dockerfile
docker/wp-base/install-plugins-and-themes.py

- `install-plugins.py` now can accept any number of mu-plugins from anywhere it does plugins
- The list is sourced from the Ansible state using the same technique as we previously did with plugins
- Still no effect Ansible-side

Manage mu-plugins in Ansible config

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Used in a bunch of sites of /srv/subdomains — Currently causing a number of broken symlinks

Add simple-sitemap plugin

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Some hacks in epfl/menus/epfl-menus.php depend on internal details of
Poylang. This unintended upgrade broke all menus on www.epfl.ch

Pin Polylang to a version before 2.6

---

docker/wp-base/Dockerfile

This is known as DEV_WP_4_SYMLINK in http://go.epfl.ch/wp5-design-doc
The elegant thing would be to have /wp/4 be a directory; however,
given the current layout of symlinks on the NAS share, this is not
currently possible. The plan is therefore to
1. Push this here change to production
2. Resymlink all sites with a two-symlink scheme similar to the one
Kubernetes uses for secrets and ConfigMaps
3. Do The Right Thing in the image

Make /wp/4 exist

---

docker/wp-base/wordpress-anywhere.patch

This lets `require_once("wp_load.php");` do the right thing in a
symlinked site, also when invoked from a .php script up to one
directory deep inside a plug-in.
In turn, this will let us to improve on things like [jahia2wp#1037](https://github.com/epfl-idevelop/jahia2wp/pull/1037)

Walk higher up to find a wp-config.php

---

ansible/roles/wordpress-instance/tasks/symlink.yml

- .ini files are OK
- In case other files are left over, signal them (by going orange) but don't erase them

More prudent cleanup operations after symlinking

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Le plugin cache-control a été supprimé du store WordPress le 5 juillet 2019 => https://fr.wordpress.org/plugins/cache-control/
Ceci entraine un problème de la création de l'image chaque nuit dans Jenkins. Afin de faire en sorte que cela continue à fonctionner, il a été choisi de récupérer le code du plugin (dans un autre site déjà déployé) et de l'intégrer dans le repo jahia2wp (via PR ).
Par la suite, il faudra définir si on continue avec ce code récupéré et plus maintenu ou si on trouve un autre plugin.

Use code from our repo because plugin deleted from WordPress store

---

ansible/roles/wordpress-instance/tasks/plugins.yml

- Suite à l'ajout du plugin spécifique à la bibliothèque dans le repo jahia2wp, ajout de celui-ci dans l'image wp-base
**Note**
L'image a été build en local afin de valider la chose.

Add Library specific plugin

---

docker/wp-base/Dockerfile
docker/wp-base/clearstatcache-wp-import.patch

No idea why this worked before, or why it started failing - However,
in the current setup, all filesize() calls read out to zero, despite
the file having the correct size.

Bugfix: clearstatcache() before reading file sizes

---

docker/httpd/dyn-vhost.conf

This fixes a breakage introduced in
https://github.com/epfl-idevelop/wp-ops/commit/a4bc309e5913a1be950ab4703ad2b88140ff54aa
whereby all log files have a literal `$(hostname)` in the name.

Use an environment variable (not command substitution) for HOSTNAME

---

docker/httpd/php.ini

As a DevOps operator, we want to be able to move from e.g. WordPress 4 to WordPress 5 by atomically mutating one symlink. The only thing that stands in the way of that goal after #103  is that PHP won't seem to revalidate some kind of cache until we restart Apache.
- Found poorly documented `opcache.revalidate_path` that sounds related to the issue at hand
- Looked at source code, sorta willing to believe that this could do the trick
- Let's find out by merging this PR and see what happens to the QA rig

Bugfix: serving off stale PHP code when updating symlinks

---

docker/wp-base/Dockerfile
docker/wp-base/install-plugins-and-themes.py
docker/wp-base/wordpress-anywhere.patch

Layout is like
```
/wp
|-- 4 -> 4.9.10
|-- 4.9.10
|   |-- index.php
|   |.......
|-- 5 -> 5.2.2
|-- 5.2.2
|   |.......
```
(more in the commit messages)
- Use `patch` instead of `git apply`, because someone did a one-line
cosmetic change in WordPress branch 5.x in the vicinity of where
`wordpress-anywhere.patch` used to apply cleanly
- Patch the patch to support `patch -p0`
- Turn a bunch of RUN commands into `for` loops, so as to accomodate
`WORDPRESS_VERSION_LINEAGES` now being plural

 Support multiple versions of WordPress in one image 

---

docker/httpd/php.ini

This reverts commit b0ede35906c37e75ca4a1d381efc2c560e12e206 (aka #104)
After further testing, it turns out that the culprit is not the
opcache, but rather, the NFS client cache. We can make this work with
no changes to php.ini.

Revert "Set opcache.revalidate_path = 1"

---

docker/wp-base/Dockerfile

This lets a site stipulate that it doesn't want to migrate to WP
5.3 (yet).

Add minor-version symlinks to /wp

---

ansible/inventory/prod/wordpress-instances
ansible/inventory/test/wordpress-instances
ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/symlink.yml
ansible/roles/wordpress-instance/templates/symlinks-lib.sh

- `symlink.yml` is no longer guarded by `tags: never`. Instead of conscious operator action, what decides whether a site needs its symlinks checked on a regular basis is now its so-called “hostvars”, set by the inventory script
- Hard-code the set of such sites to be all of `www`, `labs` and `inside` DeploymentConfigs in production, as well as those sites in `subdomains` that use the `epfl-light` theme; and sites under `migration-wp.epfl.ch/htdocs/labs` on the test platform
- Don't enter maintenance mode anymore when there is no need to do so
- Treat the “main” symlink (the `wp → /wp/4` one at the WordPress site's top level) specially; set it up first (before the other ones); update it atomically (and thus, don't enter maintenance mode); revalidate NFS cache thereof on the serving pods …

`wpsible -t symlink` mainstreaming

---

docker/httpd/php.ini

This brings back #104 by reverting #105 a.k.a. commit cd6f9b5ea75a79a1fa605a6b32fbebd6e56a9f42.
Soooooo... It looks like this change, *together* with NFS symlink
revalidation, is what makes atomic updates of the `wp` symlink work.
The reproduction method is as follows:
<ol>
<li> Create script `wp-content/uploads/wpversion.php` that goes like
<pre>
&lt;?php
require_once( &lowbar;&lowbar;DIR&lowbar;&lowbar; . '/../../wp-load.php' );
echo "\$wp_version = $wp_version\n";
echo "\$wp_db_version = $wp_db_version\n";
</pre></li>
<li> Have it continually queried with `curl`, e.g. <pre>
uri=https://migration-wp.epfl.ch/labs/dcsl/wp-content/uploads/wpversion.php
while sleep 1; do (set -x; curl -sS -H "Cache-Control: no-cache" $uri ) ; done
</pre></li>
<li> Update the main symlink (the one whose name …

Bugfix: serving off stale PHP code when updating symlinks 

---

ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/vars/plugin-vars.yml

Plugin activation is not operational yet, but will be conditional to a WordPress version check.

Add plugin wp-gutenberg-epfl

---

ansible/inventory/prod/wordpress-instances
ansible/inventory/test/wordpress-instances
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/tasks/configure.yml
ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/tasks/symlink.yml
ansible/roles/wordpress-instance/vars/plugin-vars.yml
ansible/roles/wordpress-instance/vars/symlink-vars.yml

... And do so correctly in the face of the upcoming transition to WP 5.x.
- Flesh out the `wordpress_plugin` custom action, so that it now honors `state: symlinked` or `state: absent` (`state: must-use`  is still to-do)
- Stop managing the symlinks in `wp-content/plugins` as part of the main WP install in `symlink.yml`, now that `plugins.yml` takes care of it.
Demo:
<pre>wpsible -l migration-wp-labs-dcsl -t symlink,config,plugins -e '{"wp_destructive": {"migration-wp-labs-dcsl": "config"}}' -v</pre>
<pre>wpsible -l migration-wp-labs-dcsl -t symlink,config,plugins -e '{"wp_destructive": {"migration-wp-labs-dcsl": "config"}, "wp_ensure_symlink_version": "4"}'</pre>

Manage plug-ins with Ansible

---

ansible/roles/wordpress-instance/tasks/backup.yml
ansible/roles/wordpress-instance/tasks/main.yml

As per today's discussion in the daily stand-up, `-t backup.data` will come in handy soon. (`-t backup` was already working, but we don't want to waste the time and disk space.)

Implement `-t backup.code`, etc. as subsets of `-t backup`

---

ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/symlink.yml

The truth is that symlinking *will* destroy code e.g. if you have a site whose PHP has been hand-edited, then those changes will be rolled back.
One must now say
```
"wp_destructive": {"migration-wp-labs-dcsl": "config,code"},       # ...
```
instead of just
<s><pre>"wp_destructive": {"migration-wp-labs-dcsl": "config"},     # ...</pre></s>

Fix up wp_destructive requirements for symlinking

---

ansible/roles/wordpress-instance/vars/wp-destructive.yml

That is, one now says
```
"wp_destructive": {"migration-wp-labs-dcsl": ["config", "code"]},
```
instead of <s><pre>
"wp_destructive": {"migration-wp-labs-dcsl": ["config,code"]},
</pre></s>

Use proper JSON data structure in wp_destructive

---

ansible/roles/wordpress-instance/tasks/facts.yml

There was a single-letter typo

Fix `wp_is_symlinked` fact

---

ansible/inventory/prod/wordpress-instances
ansible/inventory/test/wordpress-instances
ansible/roles/wordpress-instance/vars/openshift-vars.yml

This way, all Wordpress instances (including those from [branch `feature/wp-int`](https://github.com/epfl-idevelop/wp-ops/tree/feature/wp-int)) have an `openshift_dc`.

Hoist `openshift_dc` from inventory to `openshift-vars.yml`

---

ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/tasks/generate.yml
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/vars/plugin-vars.yml

This fixes the bug whence every site one ran Ansible on, would go into "coming soon" mode.
- Develop wordpress_plugin.py to distinguish "installation" desired state (e.g. `absent`, `installed` and `symlinked`) and "activation" desired state (`active`, `inactive`) in the `state: ` task argument
- Fully support `state: ` being a list
- Use set arithmetic to find out what is to be done
- Cut corners by refusing to install without symlinks (so that we don't have to fiddle with `wp plugin install` for now), and doing nothing on must-use plugins (because some of ours use more than one top-level file)

Distinguish "symlinked" from "active" in plugins.yml

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Mise à jour de la liste des plugins à mettre dans l'image
- Ajout de EPFL-Menus
- Désactivation de tinymce-advanced quand on est en Gutenberg

Add EPFL-Menus, do not activate tinymce-advanced if gutenberg

---

docker/mgmt/Dockerfile
docker/mgmt/new-wp-site.sh

- Pros: takes no parameters
- Cons: doesn't install any plugin, mu-plugin etc. (That is the job of Ansible)
- Where: in `/usr/local/bin` of the mgmt image (so that if you don't want to use it, you don't have to)
- Why: first use-case is for [wp-dev](https://github.com/epfl-idevelop/wp-dev), but we can also actually create sites with this.
Features:
- repeatable
- every destructive step controls whether it needs doing
- credentials are persisted in `wp-config.php` even before the database is created, and retrieved from there if the script fails mid-way (which it shouldn't)
- URL and site title are guessed from the EPFL directory layout
- creates actual, working admin user (should be removed later e.g. after installing EPFL Tequila plug-in)

Shell script to create a WordPress site

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Réactivation du plugin TinyMCE Avanced pour tous (en lien avec https://github.com/epfl-idevelop/jahia2wp/pull/1107)

Allow TinyMCE for all

---

docker/mgmt/new-wp-site.sh

Improved features to create a new WP site from the `new-wp-site.sh` script, including:
* add symlinked mu-plugins, plugins and themes
* activate wp-theme-light by default
* activate most of mu-plugins and plugins

[feature] improved script to create a site

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Ajout du plugin PDF Viewer en mode bloc dans l'image.
Lié à la PR https://github.com/epfl-idevelop/jahia2wp/pull/1111

Add PDF Block plugin

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Après l'installation du plugin "bloc" pour afficher un PDF (https://github.com/epfl-idevelop/jahia2wp/pull/1111) et la transformation des pages pour utiliser celui-ci, on peut supprimer l'ancien, celui sous forme de shortcode.

Remove old shortcode plugin from image

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Ajout du plugin `EPFL_block_white_list.php` à la construction de l'image.
PR d'ajout du MU-Plugin: https://github.com/epfl-idevelop/jahia2wp/pull/1118

Install MU-Plugin for block white list

---

ansible/roles/wordpress-instance/tasks/plugins.yml

- Active le plugin `epfl-menu` lors des déploiements Gutenberg
- Supprime le plugin `epfl` de l'image.
**NOTE**
- Merger d'abord https://github.com/epfl-idevelop/jahia2wp/pull/1099 et suivre doc dans la PR 1099

[wait] Activate epfl menus in gutenberg

---

docker/wp-base/Dockerfile
docker/wp-base/symlink-wp-versions.sh

Bring WordPress 5.3 into the image but **don't** make the `/wp/5 → /wp/5.3` symlink yet.
- Refactor the symlink-making logic out of the `Dockerfile` and into a shell script, so as to contain its growing complexity

Bring WordPress 5.3 into the image on an experimental basis

---

docker/wp-base/Dockerfile

Recently we discovered that newly-installed sites complain about `tinymce-advanced` plugin being too recent w.r.t. the WordPress version (e.g. `tinymce-advanced` version 5.3.0 for WordPress 5.2.1). Fix that.
- Examine WordPress repository through its API to find out and use the most recent version of `tinymce-advanced` per WordPress version lineage:
- 4.8 for WordPress 4.9
- 5.`x` for WordPress 5.`x`, for known values of `x` so far (2 and soon, 3)
- Create a wart in the Dockerfile to remove and reinstall `tinymce-advanced` plugin according to these findings

[fix] One tinymce-advanced version per WordPress version

---

ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/vars/symlink-vars.yml

Fix 1: when a plugin or mu-plugin symlink was done "the old way" (e.g. to `/wp/wp-content`), which is now incorrect (as it pins the version of a particular plugin back in time), Ansible currently doesn't detect and fix it.
- Introduce a new state in `get_current_state()`, `symlink_damaged`
- It turns out that said `get_current_state()` was incorrectly assuming that everything is a plugin (not a must-use plugin); fix that
Fix 2: (more like a stop-gap) Install `EPFL_google_analytics_hook.php` everywhere

Fixes to Ansible plugin and mu-plugin management

---

ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/vars/symlink-vars.yml

- Refactor `ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py` to deal with a multiplicity of files
- (Almost) stop mixing up install- and activation-related states (still do so on the “expected” side)
- We are now able to symlink a mu-plugin that was not already there, and do so in a smart way (i.e. computed from a Jinja template)

Manage mu-plugins and plugins consisting of more than one file — The Right Way™

---

ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py

- Separate data flows between activation and installation states more clearly
- Fix some confusion between both ends of a symlink (as usual)

Fix: plugins deletions didn't work

---

docker/wp-base/Dockerfile
docker/wp-base/cortneyray/wp-cli-polylang/PolylangHelperFunctions.php
docker/wp-base/cortneyray/wp-cli-polylang/Polylang_Command.php
docker/wp-base/cortneyray/wp-cli-polylang/README.md
docker/wp-base/cortneyray/wp-cli-polylang/composer.json

Investigation pour savoir pourquoi la commande `wp polylang language add` qui vient du package WPCLI `cortneray/wp-cli-polylang` ne fonctionnait plus pour les versions Polylang > 2.2.8.
Adaptation du code pour corriger la chose et supporter les versions de Polylang:
- plus grand que 2.2.8 et jusqu'à 2.5.x 
Passage d'un tableau non associatif (dans `settings/languages.php`) à un tableau associatif pour lister les langages disponibles, )c'est ça qui faisait péter nos installations avec `jahia2wp.py`) 
- à partir de 2.6.x 
Le tableau associatif est maintenant "retourné" et plus initialisé (dans `settings/languages.php`)
Selon discussion avec @lvenries , une PR a été faite sur le repo officiel du package (https://github.com/cortneyray/wp-cli-polylang/pull/1) mais au vu du peu d'activité …

[WAIT] Add cortneray Polylang WPCLI package with patch

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Said plugin was extracted out of jahia2wp using the following script:
```
git clone ~/Dev/WordPress/volumes/wp/jahia2wp epfl-menus
cd epfl-menus
git checkout origin/release2018
git checkout -b release2018
git filter-repo --path data/wp/wp-content/plugins/epfl-menus \
--path-rename 'data/wp/wp-content/plugins/epfl-menus/epfl-menus-admin.css:epfl-menus-admin.css' \
--path-rename 'data/wp/wp-content/plugins/epfl-menus/epfl-menus-admin.js:epfl-menus-admin.js' \
--path-rename 'data/wp/wp-content/plugins/epfl-menus/epfl-menus.php:epfl-menus.php' \
--path-rename 'data/wp/wp-content/plugins/epfl-menus/wpcli.php:wpcli.php' \
--path-rename 'data/wp/wp-content/plugins/epfl-menus/lib:lib' \
--force
git checkout -B master
git remote add origin git@github.com:epfl-idevelop/wp-plugin-epfl-menus.git
git …
```

Check out the epfl-menus plugin from its new home

---

ansible/inventory/prod/wordpress-instances
ansible/inventory/test/wordpress-instances

- Work out the argument to `sys.path.append` in a way that doesn't
depend on which directory is current
- Use a `#!/usr/bin/env` shebang, for people who don't have a
`/usr/bin/python3` (e.g., Mac OS X) or don't want to use it (e.g.,
`virtualenv`)

[fix] Portability warts in new Python inventory scripts

---

.travis.yml
docker/mgmt/Dockerfile

- New `ARG WP_OPS_BRANCH` argument to `docker/mgmt/Dockerfile`, which lets one build the `mgmt` to include a specific branch of `wp-ops`
- Use that feature in `.travis.yml` so that the entire build is done on the pull-request branch

Install Ansible into the mgmt image

---

Makefile

Right now we save only all configmaps in each namespace (wwp and
wwp-test).
- Created one Keybase repository per Kubernetes namespace in use
- Add Makefile to `oc get -o yaml` the objects, create an automated
git commit, and push
- Still needed: wp-dev should daisy-chain `make checkout` to wp-ops

[feature] Back up select Kubernetes objects to a Keybase-encrypted git

---

ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py

Depuis le début de la migration des plugins que l'on a développés afin qu'ils aient chacun leur propre repo Github, des installations de plugin via Ansible ne fonctionnaient plus car le nom du repo ne correspondait plus au nom du plugin (ex: `epfl-menus` vs `wp-plugin-epfl-menus` ) et le script tentait d'installer un plugin qui portait le nom du repo
Ajout d'un petit check pour savoir si le `from` que l'on a mis dans le fichier `plugins.yml` est un repo Github ou pas au moment d'identifier si c'est un fichier qui est référencé

Do not consider github repo as file when installing plugin

---

README.md
ansible/inventory/wp-veritas/wp_veritas_inventory.py
ansible/roles/awx-poc-vpsi/vars/main.yml
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/tasks/restore-over-ssh.yml
ansible/roles/wordpress-openshift-namespace/vars/continuous-integration-vars.yml
ansible/roles/wordpress-openshift-namespace/vars/image-vars.yml
docker/cronjob/Dockerfile
docker/httpd/Dockerfile
docker/mgmt/Dockerfile
docker/wp-base/Dockerfile
docker/wp-base/install-plugins-and-themes.py

Following the rename of the epfl-idevelop GitHub organization to epfl-si today, we want to update all pointers (despite the old addresses still working for now).

[janitor] github.com/epfl-idevelop → github.com/epfl-si

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Petit "piège" suite à l'implémentation d'un "Action Plugin" pour traiter les options des plugins... il y avait des options pour Accred qui étaient codées depuis longtemps avec des valeurs bidon mais jamais mises à jours dans les sites car le "Action Plugin" pour faire le boulot n'existait pas... et là, du coup, ça pète le site car ça mets des valeurs par défaut...

Dont update unit infos

---

ansible/inventory/wp_inventory.py
ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py
ansible/roles/wordpress-instance/action_plugins/wordpress_option.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/action_plugins/wordpress_theme.py
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/tasks/themes.yml
ansible/roles/wordpress-instance/vars/accred-vars.yml
ansible/roles/wordpress-instance/vars/theme-vars.yml

- Correction d'un bug dans la gestion des plugins
- Ajout de la gestion de la mise à jour des options de plugins, y compris de celles qui sont sérialisées (passage par PHP pour les désérialiser et les encoder en JSON)
- Réorganisation du code pour mettre plus d'éléments dans la classe parente
- Ajout de la gestion des thèmes
- Nouvelle information récupérée lors de l'inventaire "mini", en l'état du thème courant. 
- Les informations sur les unités sont maintenant récupérées lors de l'inventaire "mini" également
- Utilisation des informations d'unité et de thème pour mettre à jour respectivement la configuration accred et du thème. Aucun changement ne sera fait pour ces éléments si on lance avec un inventaire de ce qui existe. Par contre, si l'inventaire vient de WP-Veritas, là, il …

More on Actions Plugins

---

ansible/roles/wordpress-instance/tasks/plugins.yml

On s'assure que la version du plugin TinyMCE est la même que dans la PR https://github.com/epfl-si/jahia2wp/pull/1122 car on se basait sur la version qui est dans le store WordPress, donc pas alignée avec ce qu'on installait avec `jahia2wp`. Donc, si on symlinquait le plugin, on passait sur la version de l'image, qui était plus récente et pas 100% compatible avec notre version de WP. Elle "était" plus récente car il semblerait qu'entre temps les développeurs du plugins l'ait supprimée du store WordPress donc ça ne nous impacte pas. Mais pour éviter tout impact, on "force" le ZIP à utiliser pour mettre dans l'image. Et il a été choisi de mettre l'URL du ZIP qui est dans Jahia2WP comme ça si un jour on vire la limitation là, on virera à tous les coups le ZIP et le build de l'image plantera …

Use right version for TinyMCE Advanced

---

docker/monitoring-menus-probe/index.js

“Last success” and “failing since” time series, as epoch numbers, per originating URI, menu slug (e.g. `top`, `footer`), and language.
- More work in the prober to scrape the new timeseries
- Work in tandem with https://github.com/epfl-si/wp-plugin-epfl-menus/pull/3 for the labels (with temporary fallback mode, whence only a not-so-helpful menu slug can be computed)

[Feature] More menu monitoring

---

ansible/roles/wordpress-instance/tasks/plugins.yml

New repo : https://github.com/epfl-si/wp-mu-plugins
Linked with https://github.com/epfl-si/jahia2wp/pull/1162

Set mu-plugins source to the new repository

---

ansible/ansible.cfg
ansible/roles/wordpress-instance/action_plugins/wordpress_wpcli.py
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/vars/plugin-vars.yml

- Ajout d'un "ActionPlugin" (notion Ansible) pour pouvoir exécuter des commandes WP-CLI spécifiées dans les fichiers YAML de configuration des plugins, thèmes et autres...
- Suite à PR https://github.com/epfl-si/wp-plugin-epfl-intranet/pull/1, utilisation de WP-CLI pour activer et configurer le plugin `epfl-intranet`. 
L'utilisation de WP-CLI permet de faire en sorte que le fichier `.htaccess` soit correctement modifié lors de l'activation ou désactivation.
- Ajout d'un peu de config Ansible pour augmenter les perfs lors de connexions SSH
- Changement de la manière dont on détermine si on est sur un site "Inside" (on utilise aussi la catégorie au lieu de passer par le WPENV, c'est plus cohérent d'utiliser la même source de données).
- Regroupement des configurations Accred en une seule.

Use WPCLI for EPFL-intranet configuration

---

ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/vars/plugin-vars.yml

- Ajout d'une catégorie de site "admin" (non présente dans `jahia2wp` mais existante dans WP-Veritas)
- Catégorie utilisée par le site wp-manager.epfl.ch
- Association du plugin "MainWP" à cette catégorie

Add mainwp plugin to image

---

ansible/inventory/wp-veritas/wp_veritas_inventory.py
ansible/roles/wordpress-instance/action_plugins/wordpress_option.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin_epfl_intranet.py
ansible/roles/wordpress-instance/action_plugins/wordpress_theme.py

Quelques corrections pour que l'option `--check` d'Ansible puisse fonctionner correctement.
- Remise en place de la catégorie `all-wordpresses` qui est référencée dans Ansible
- Ajout de check dans les ActionPlugin pour faire en sorte de détecter si on exécute en mode `--check` et ne rien faire.

Fix WP Veritas inventory --check

---

ansible/roles/wordpress-instance/vars/accred-vars.yml

Après avoir fait des tests avec la commande du genre : 
`./wpsible -l www__labs__mackenziemathis_lab --check --wp-veritas -t configure,plugins,themes,symlink -e '{"wp_destructive": {"www__labs__mackenziemathis_lab": ["config","code"]}, "wp_ensure_symlink_version": "5.2", "wp_is_managed":true}' `
Il semblerait que la valeur de wp_administrator_group n'était pas la bonne

Fix value of wp_administrator_group

---

ansible/inventory/prod/wordpress-instances
ansible/inventory/test/wordpress-instances
ansible/inventory/wp-veritas/wp_veritas_inventory.py
ansible/inventory/wp_inventory.py
ansible/roles/wordpress-instance/lookup_plugins/wpveritas.py
ansible/roles/wordpress-instance/vars/accred-vars.yml
ansible/roles/wordpress-instance/vars/main.yml
ansible/roles/wordpress-instance/vars/plugin-vars.yml
ansible/roles/wordpress-instance/vars/theme-vars.yml
ansible/wpsible

- New `lookup("wpveritas")` lookup plug-in
- Use it to look up `wp_unit_name`, `wp_unit_id`, `wp_site_category` and `theme_name` from the authoritative source
- Stop trying to gather surrogates for these values at inventory time, thereby bringing back acceptable performance to the `wpsible` inventory phase

[Feature] wp-veritas integration

---

ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py
ansible/roles/wordpress-instance/action_plugins/wordpress_option.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin_epfl_intranet.py
ansible/roles/wordpress-instance/action_plugins/wordpress_theme.py

Split huge `WordPressActionModule` class in two
- `WordPressActionModule` knows about symlinks, rimrafs, and WordPress paths and commands
- `WordPressPluginOrThemeActionModule` additionally knows about plugin
or theme enumeration / activation / deactivation, as well as
`._name`, `._type` and `._mandatory`
- Move "option is unchanged." behavior into the right subclass

Refactor classes in wordpress_action_module

---

ansible/inventory/wp-veritas/wp_veritas_inventory.py
ansible/inventory/wp_inventory.py
ansible/roles/wordpress-instance/vars/main.yml

- `wp_ensure_symlink_version` needs not be a per-host variable anymore
- `openshift_namespace` was unconditionally wrong
- `ansible_host` was wrong on test instances
And refactoring to go with it.

[Fix] Inventory hostvars for WordPress sites

---

docker/mgmt/Dockerfile

This works around (speeds up) a possible bad configuration in the client. There is no X11 support whatsoever in the mgmt image.

Disable ssh X11 forwarding on the mgmt container

---

ansible/roles/awx-instance/filter_plugins/imagestream_tag_map.py
ansible/roles/awx-instance/handlers/main.yml
ansible/roles/awx-instance/tasks/k8s-builds.yml
ansible/roles/awx-instance/tasks/k8s-images.yml
ansible/roles/awx-instance/tasks/k8s.yml
ansible/roles/awx-instance/tasks/main.yml
ansible/roles/awx-instance/tasks/ops.yml
ansible/roles/awx-instance/templates/pg_env.sh
ansible/roles/awx-instance/vars/main.yml
ansible/roles/awx-instance/vars/ops-vars.yml

Previously:
- AWX was not working in production, because it lacked an image for `wp-awx-task` which is only being built in the test namespace;
- the AWX backup and restore operations (`-t awx.dump` and `-t awx.restore` in [`roles/awx-instance/tasks/ops.yml`](https://github.com/epfl-si/wp-ops/blob/master/ansible/roles/awx-instance/tasks/ops.yml)) were broken, because `/etc/tower/conf.d/environment.sh` went away with RabbitMQ.

[Fix] AWX in production; AWX dump and restore

---

ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/action_plugins/wordpress_theme.py
ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/tasks/themes.yml

- Remove all short-circuit code that was turning --check's into skip's
- Plumb an optional `also_in_check_mode` parameter down the whole
`wordpress_action_module.py`
- Tell Ansible to go ahead with shell commands when this parameter is set
Note that this is independent from the `update_result=` data flow, so one could theoretically use a *destructive* command in check mode, and still check orange / green correctly. (Not suggesting that one *should*)

[fix] `--check` mode for `-t plugins,themes`

---

ansible/roles/wordpress-instance/action_plugins/wordpress_facts.py

Defensive programming for when the `wp-config.php` file doesn't exist

[fix] Another KeyError hazard

---

ansible/inventory/wordpress-instances.py
ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py
ansible/roles/wordpress-instance/action_plugins/wordpress_facts.py

As it turns out, #223 could have benefited from more testing...
- Fix typo in an error code path
- Moar `also_in_check_mode=True`
- Set (and reset) check mode support correctly prior to invoking `self._execute_module`

[Fix] Check mode again

---

ansible/playbooks/filter_plugins/tags.py
ansible/roles/wordpress-instance/tasks/backup.yml
ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/symlink.yml
ansible/roles/wordpress-instance/vars/main.yml

Enumerate the tags by walking all YAML task files in a filter_plugin instead.

[refactor] The return of `tags: always`

---

ansible/roles/awx-instance/tasks/container-group.yml
ansible/roles/wordpress-instance/vars/jahia2wp-vars.yml
ansible/roles/wordpress-openshift-namespace/tasks/mgmt.yml
ansible/roles/wordpress-openshift-namespace/vars/secrets-wwp-test.yml
ansible/roles/wordpress-openshift-namespace/vars/secrets-wwp.yml
docker/mgmt/docker-entrypoint.sh

We can now stop keeping the master secret of the EPFL WordPress platform on NFS.
- Keep `WP_ENV` as a “free-floating” variable, that must be passed around whenever jahia2wp gets invoked
- Put the other `WP_*` variables into a ConfigMap and the MYSQL_* variables into a Secret
- Generate `/etc/profile.d/k8s-env.sh` from within `docker-entrypoint.sh` so that ssh users also obtain these variables in their environment

[Feature] Propagate environment through ConfigMaps and Secrets

---

ansible/.gitignore
ansible/wpsible

We will never have to worry about versions of Python, Ansible, Ansible Galaxy modules, or EYAML again. Or if we do, we can just
```
rm -rf ansible/ansible-deps-cache
```
[What is ansible.suitcase?](https://github.com/epfl-si/ansible.suitcase)

[feature] Adopt ansible.suitcase

---

ansible/inventory/wordpress-instances.py
ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/action_plugins/wordpress_unknown_plugins.py
ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/plugins.yml

- New `wordpress_unknown_plugins` action module, which only does
anything with `state: absent`
- Collect the removed WordPress plug-ins into the
`wordpress_unknown_plugins` field of the `result` (visible under
`ansible-playbook -v`)
- Supports `--check`

[feature] Remove unknown installed plug-ins

---

ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/menus.yml

As per today's work, Ansiblify the command to refresh menus (even though it would be unwise to use it yet!)
- New tasks file `menu.yml`
- Guarded by `tags: never`, so it won't fire unless we explicitly pass `-t menus.wp.refresh` (tested with `./ansible/wpsible --prod -l www__campus__services__canari`)

[feature] `wpsible -t menus.wp.refresh`

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Adaptation suite à la PR https://github.com/epfl-si/jahia2wp/pull/1169 qui renomme des plugins. On prend les nouveaux noms pour la génération de l'image.

[to merge on Wednesday, 13 May] New plugin names

---

docker/wp-base/Dockerfile

The main motivation of doing this now, is to side-step
https://github.com/composer/composer/issues/8586 by upgrading
PHP's composer tool.
- Upgrade to Ubuntu focal, PHP 7.4 and node 14

[upgrade] wp-base software

---

docker/mgmt/new-wp-site.sh

Basically, the DB host is not always `db`.

[Fix] Bad assumptions in `new-wp-site`

---

ansible/inventory/test/group_vars/openshift_namespaces_dev
ansible/roles/awx-instance/tasks/k8s.yml
ansible/roles/wordpress-openshift-namespace/tasks/deploymentconfig-httpd.yml
ansible/roles/wordpress-openshift-namespace/tasks/disk-usage-report.yml
ansible/roles/wordpress-openshift-namespace/tasks/mgmt.yml
ansible/roles/wordpress-openshift-namespace/tasks/monitoring.yml
ansible/roles/wordpress-openshift-namespace/vars/main.yml

- Fully flesh out the `httpd` DeploymentConfig objects (test-side only, for now)
- Refactor to eliminate the "text" form of `openshift:` tasks; use actual YAML instead
- Rewrite decimal file modes into octal

[feature] More k8s in Ansible

---

ansible/inventory/wordpress-instances.py
ansible/wpsible

- Mute useless indications from `oc projects` (for versions >= 4.0)
- Ensure to run the Python inventory using the suitcase's Python interpreter (fixes #277)
- Equal opportunity for “playbook-less” invocations:
- move oc_check call inside platform_check
- do `platform_check` also in playbook-less mode

[fix] Small issues in the `wpsible` wrapper

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Add the check compatibility flag on task that register a state needed by other tasks
Fix https://github.com/epfl-si/wp-ops/issues/278

Add the check compatibility on "registering" tasks

---

ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/vars/plugin-vars.yml

Cette PR (Fix #280 ) a pour but d'activer et de "désarmer" (settings: disabled) le plugin coming-soon si ce dernier est inactif.
Voila, un petit schéma qui permet de mieux comprendre les différents cas gérés par Ansible pour ce plugin:
Schéma: @ponsfrilus

[feature] manage inactive coming soon

---

ansible/roles/wordpress-instance/action_plugins/wordpress_plugin_epfl_intranet.py

La manière de fonctionner du plugin `epfl-intranet` a changé (https://github.com/epfl-si/wp-plugin-epfl-intranet/pull/3) donc mise à jour en conséquence:
- Nouvelle commande pour "l'activation" et l'initialisation des paramètres
- On désactive maintenant complètement le plugin dans le cas où il ne faudrait pas protéger le site web (à priori, on n'arrivera jamais dans cette section de code car si on ne veut pas de protection, le plugin ne sera pas installé/activé par Ansible).

Update WP-CLI commands to fit new plugin behaviour

---

ansible/inventory/wordpress-instances.py
ansible/roles/awx-instance/tasks/k8s-builds.yml

- Build the awx-runner on top of the new, RH8-based image
- Inventory script should not attempt to run through [ansible-suitcase](https://github.com/epfl-si/ansible.suitcase) on AWX, because it is not available there

[fix] AWX was broken in multiple ways

---

ansible/roles/wordpress-openshift-namespace/tasks/deploymentconfig-httpd.yml

A smooth transition from “unmanaged” to “managed” on these objects is impossible for several reasons.

[mollyguard] Do not mess with httpd-* DeploymentConfigs for now.

---

docker/mgmt/Dockerfile
docker/mgmt/lnav/apache-hostname-leading.json

WordPress logs uses the so-called "vcommon" Apache log format, with
the name of the serving virtual host as an additional field in first
position. lnav won't grok these, unless taught how, so there.
- Snarf JSON file found at
https://groups.google.com/g/lnav/c/aWLs2PCTtVU/m/1WkvoW7OAwAJ
- Arrange for the mgmt Docker image to have it

[add] Custom lnav parser for our Apache logs

---

ansible/.interactive-playbooks/filter_plugins/tags.py
ansible/.interactive-playbooks/main.yml

Make `--skip-tags` work nicely with the role skip feature.
Picture obtained with
```
./ansible/wpsible -l test_migration_wp__labs__urbangene -e '{"wp_destructive": {"test_migration_wp__labs__urbangene": ["config"]}, "wp_version_lineage": "5.4"}' --skip-tags plugins,themes
```

[fix] Skipping the WordPress instance role vs. --skip-tags

---

ansible/roles/wordpress-instance/tasks/configure.yml
ansible/roles/wordpress-instance/tasks/samples.yml
ansible/roles/wordpress-instance/tasks/site-metadata.yml

When a `when:` clause depends on the `.stdout` of a former command, do
check that that command was not `.skipped`

[fix] `--check` support

---

docker/wp-base/symlink-wp-versions.sh

Now `/wp/5` points to `/wp/5.4`
Also, remove the WordPress 4.x living (by symlink) directly under `/wp`

[feature] Unpin WordPress version

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Ajout d'un plugin PDF Flipbook. Ce plugin utilise un shortcode et n'a aucune interface utilisateur graphique donc l'ajouter sera complètement transparent pour l'utilisateur
Par la suite viendra un nouveau bloc qui fera office d'interface pour utiliser ce shortcode.

Add PDF plugin flipbook

---

ansible/inventory/wordpress-instances.py

wp-veritas has no category anymore, it's a list of categories. The inventory script `wordpress-instances.py` is still using category: this fix it.

[quickfix] category to categories

---

ansible/roles/wordpress-instance/tasks/configure.yml
ansible/roles/wordpress-instance/tasks/samples.yml
ansible/roles/wordpress-instance/tasks/site-metadata.yml

AFAICT the `.skipped` value is only present when true (i.e. when running Ansible with the `--check` argument), so one needs to check that it exists before using it. I haven't found something on it in the documentation, but you can start here https://docs.ansible.com/ansible/latest/reference_appendices/common_return_values.html#skipped.

[quickfix] Ansible `.skipped` return value only present when true

---

.travis.yml
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/vars/plugin-vars.yml

This PR includes:
- no more travis exclude of wpforms-epfl-payonline
- wp-veritas categories "Payonline" add wpforms plugin as well
- plugin wpforms-epfl-payonline now has a zip with a subfolder in it, so the [latest release download url](https://github.com/epfl-si/wpforms-epfl-payonline/releases/latest/download/wpforms-epfl-payonline.zip) can be used

[feature] symlink wpforms

---

ansible/inventory/wordpress-instances.py

`WWP_NAMESPACES=wwp-test,wwp ./ansible/inventory/wordpress-instances.py |diff -U3 inventory.GOLD -`
```
--- inventory.GOLD	2020-08-12 10:23:20.000000000 +0200
+++ -	2020-08-12 10:47:45.000000000 +0200
@@ -19265,15 +19265,8 @@
},
"all_wordpresses": {
"children": [
-            "prod_form",
-            "prod_inside",
-            "prod_labs",
-            "prod_sandbox",
-            "prod_subdomains_lite",
-            "prod_subdomains",
-            "prod_www",
-            "test_dev",
-            "test_int"
+            "prod_wordpresses",
+            "test_wordpresses"
]
},
"prod_form": {
@@ -20837,6 +20830,17 @@
"nrg2021"
]
},
+    "prod_wordpresses": {
+        "children": [
+            "prod_form",
+            "prod_inside",
+            "prod_labs",
+            "prod_sandbox", …
```

[feature] `prod_wordpresses` and `test_wordpresses` Ansible groups

---

docker/wp-base/Dockerfile

According to `grep`, the only place in the code base that still uses
this is
https://github.com/epfl-si/jahia2wp/blob/release2018/src/jahia2wp-utils/intlabs_to_prodlabs_backup.sh#L20

[delete] wp-cli-polylang package

---

ansible/.interactive-playbooks/main.yml

Use a computed `hosts` field, rather than a `when` clause. Two
benefits: the code is simpler (no need for `tags: always` anymore);
and Ansible really does skip the entire block, instead of wasting time
and screen real estate to account for the number of skipped hosts (as
it now seems to do, after the changes to ansible.cfg brought by
https://github.com/epfl-si/wp-ops/pull/294)

[rewrite] tag-based guard logic on the wordpress-instance role

---

ansible/roles/awx-instance/tasks/container-group.yml
ansible/roles/wordpress-instance/filter_plugins/base64.py
ansible/roles/wordpress-instance/lookup_plugins/env_secrets.py
ansible/roles/wordpress-instance/tasks/create.yml
ansible/roles/wordpress-openshift-namespace/tasks/images.yml
ansible/roles/wordpress-openshift-namespace/tasks/mgmt.yml
ansible/roles/wordpress-openshift-namespace/vars/mgmt-vars.yml
ansible/vars/env-secrets.yml
ansible/vars/secrets-wwp-test.yml
ansible/vars/secrets-wwp.yml

Previously:
- `ansible/roles/wordpress-instances/tasks/create.yml` acquired the secrets by sourcing a file that only exists on the mgmt container
Now:
- Secrets can be looked up using `lookup("env_secrets", SECTION, VARIABLE)`; this will Do The Right Thing both on awx and on “classical” Ansible, running from the operator's workstation
- The dataflow for the corresponding secrets has been refactored and documented (through a Kubernetes Secret, into environment variables that the mgmt and awx-runner pods can consume)
Also:
- The `jahia2wp-env` ConfigMap object has been renamed to `new-wp-site-env`

[refactor] Secret passing through environment variables

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Suite à l'ajout d'un autre élément pour afficher les PDF (#307 ) et à la transformation du code pour utiliser ce nouvel élément (https://github.com/epfl-si/jahia2wp/pull/1171), on peut supprimer l'ancien block 👋

Remove old PDF viewer

---

ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/plugins.yml

- Make a `state: absent` one-shot action
- Create tag `wp.plugins.pdf`

[feature] Clean up former PDF-related plug-ins

---

ansible/inventory/wordpress-instances.py
ansible/roles/wordpress-instance/vars/main.yml

Il existe une nouvelle instance de TEST de wp-veritas : https://wp-veritas-test.epfl.ch/
On peut donc l'utiliser à la place de https://wp-veritas.128.178.222.83.nip.io/ qui devient l'instance de DEV

[feature] Use new wp-veritas test instance

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Après avoir déplacer les plugins encore présents dans jahia2wp dans leur repo git respectif, on a modifié les URLs des repo git de ces plugins.

[feature] Use new GIT Repository plugins URL

---

ansible/roles/wordpress-instance/tasks/restore.yml

This variable is only ever used under `-t restore`.

[fix] Rename `backup_restic_tag` variable to `restore_restic_tag`

---

ansible/inventory/wordpress-instances.py

This reverts commit 25dbfae5d02670ce7b9c402ee58852820224dc2c.
This was causing a group loop, because “inside” is both a WordPress
environment (as in `/srv/inside`) and a hostname (as in
`inside.epfl.ch`)

[revert] Additional groups per hostname radix

---

ansible/wpsible

[ansible.suitcase](https://github.com/epfl-si/ansible.suitcase) takes care of it these days.

[optimize] No need for `wpsible` to run `ansible-galaxy` anymore

---

docker/mgmt/Dockerfile

Cache the whole process of "apt update" AND "apt install", or fear the inconsistencies when rebuilding the image

Fix missing apt update before installing apt packages

---

docker/httpd/global-error/403.php

Errors outputed are:
- PHP Notice:  Undefined index: error_type in /var/www/global-error/403.php on line 47
- PHP Notice:  Undefined index: UNIQUE_ID in /var/www/global-error/403.php on line 13

Fix errors found in apache logs about the 403 page generation

---

ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner
docker/mgmt/Dockerfile

This lets one do e.g.
```
aws --endpoint-url=https://s3.epfl.ch s3 ls --recursive s3://svc0041-47680839aba24f7c02f160cd9d58a5e1/backup/wordpresses/
```
... given that the credentials are already available as part of the environment (via `/etc/profile.d/k8s.sh` as far as mgmt is concerned)

[feature] Install the `aws` command in ansible runner and mgmt containers

---

ansible/roles/wordpress-instance/tasks/backup.yml
ansible/roles/wordpress-instance/vars/backup-vars.yml

- Change `restic_s3_total_size` and `restic_s3_total_file_count` to be the size and file count of the snapshot tagged `latest` (as opposed to some useless theoretical aggregate sum of the sizes of all backups)
- Post new metrics to pushgateway: `restic_s3_sql_total_size`, `restic_s3_sql_total_file_count`, `s3_backup_files_total_size`, `s3_backup_sql_total_size`, `s3_backup_files_total_file_count` and `s3_backup_sql_total_file_count`

[fix] Scrape useful metrics for backup sizes

---

ansible/roles/wordpress-instance/tasks/backup.yml
ansible/roles/wordpress-instance/vars/backup-vars.yml

Repair a number of bugs in #361 and its predecessors
- Refactor to create `backup_curl_to_pushgateway_cmd`
- Carefully separate the uploads to the Prometheus push gateway: 1)
start time, 2) finish time, 3) stats
- Turn on `set -e` and `set -o pipefail` in subshells, because as it
turns out, this is not done
automatically (https://unix.stackexchange.com/a/23099/1595)
- For the same reason, cut down on subshell depth by using `echo -n`
instead of `echo "a; $(b)"`
- Separate two conjoined lines

[fix] #361

---

ansible/roles/wordpress-instance/tasks/backup.yml

- It's either `restic_` or `s3_`, not both
- The median is always `sql` or `files`
- The end is one of `_total_size` or `_total_file_count` (aligned with
what `restic --json` outputs)

[fix] Rename backup-related metrics to a uniform naming convention

---

docker/disk-usage-statistics/index.ts

- Fix a typo whence `.path` should have read `.dir`,  which resulted in all files being excluded from tallying
- Other related fixes and improvements

[fix] Account for files (not just directories)

---

ansible/requirements.yml
ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner
ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py
ansible/roles/wordpress-instance/action_plugins/wordpress_facts.py
ansible/roles/wordpress-instance/action_plugins/wordpress_option.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin_epfl_intranet.py
ansible/roles/wordpress-instance/action_plugins/wordpress_polylang_language.py
ansible/roles/wordpress-instance/action_plugins/wordpress_polylang_menu.py
ansible/roles/wordpress-instance/action_plugins/wordpress_theme.py
ansible/roles/wordpress-instance/action_plugins/wordpress_unknown_plugins.py
ansible/wpsible

Simplify `wordpress_action_module.py` and all its subclasses by moving the responsability of interfacing with Ansible into [a re-useable Ansible collection](https://galaxy.ansible.com/epfl_si/actions).
This is a pure-refactoring PR; the behavior is not supposed to change. Verified with
- `./ansible/wpsible -t wp.wipe,wp.restore,wp -l test_migration_wp__labs__dcsl -vv`
- `./ansible/wpsible -t wp.wipe,wp -l test_migration_wp__labs__dcsl -vv` (the latter requires #350 to be applied first)

[refactor] Adopt epfl_si.actions

---

ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner

As it turns out, we weren't previously using the required roles on AWX (`epfl_si.ansible_module_openshift` nor `epfl_si.ansible_module_eyaml`) and that's why we got away with not doing this sooner. In order to run https://github.com/epfl-si/wp-ops/pull/349 on AWX we'll be needing `epfl_si.actions` from now on.

[fix] Install ansible-galaxy deps into the wp-ansible-runner image

---

ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner
ansible/roles/wordpress-instance/action_plugins/cache.py
ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py
ansible/roles/wordpress-instance/action_plugins/wordpress_plugin.py
ansible/roles/wordpress-instance/meta/main.yml

This is intended to speed up `-t plugins` which in steady-state situation, keeps executing the very same command (`wp plugin list --format=json --skip-packages --skip-themes --skip-plugins'`) over and over again.
- Decorate `wordpress_plugin`'s `ActionModule` with an abstract cache keyed by `inventory_hostname` and the set of parameters passed to the `_query_wp_cli()` method
- Invalidate the cache per `inventory_hostname` whenever the `_run_wp_cli_change()` method is called
- Provide in-memory and on-disk implementations of the cache (the latter is triggered by an environment variable)

[feature] Cache wp-cli queries

---

ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner

This corrects https://github.com/ansible/awx/issues/8486 with the same patch that was accepted upstream.

[fix] Allow user-supplied labels for temp pods in container groups

---

ansible/roles/wordpress-instance/tasks/backup.yml
ansible/roles/wordpress-instance/vars/backup-vars.yml

This makes it possible to [do the needful](https://confluence.epfl.ch:8443/display/SIAC/Guide+%3A+Restic+et+les+backups+de+WordPress) when restoring  without the backup feeling whole (in fact, after this PR `wp_ignore_backup_errors` is no longer necessary)

[fix] Don't attempt to upload monitoring stats in wwp-test

---

ansible/roles/awx-instance/tasks/k8s-builds.yml
ansible/roles/awx-instance/tasks/main.yml
ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner

For some reason, we were attempting to apply the [AWX anti-affinity patch](https://github.com/ansible/awx/pull/8487) into... the ansible-runner image ☹
- Fix that
- Add the `awx.build.awx` tag to build only the patched AWX image

[fix] Patch awx in awx

---

ansible/roles/wordpress-instance/vars/backup-vars.yml
ansible/roles/wordpress-openshift-namespace/templates/prometheus-config.yml

Depuis le 11 Novembre 2020, on poussait dans la pushgateway de wwp au lieu de la pushgateway de wwp-infra.

[fix] push to wwp-infra pushgateway

---

docker/cleanup-call-logs/Dockerfile
docker/disk-usage-statistics/Dockerfile
docker/monitoring-wpprobe/Dockerfile
docker/wp-base/Dockerfile

Docker the company is done blowing through investors money, and they
are circling the drain. To be continued for all hits of `ag "FROM "`,
as the rest of the world realises same.

[fix] Migrate away as many images as possible from Docker Hub

---

ansible/roles/wordpress-openshift-namespace/templates/prometheus-menu-service-discovery.py

The caching of the sites list among the loop means that no changes happens without restarting the container, resulting in manual operations. This fixes it and the file `targets.json` used by prometheus will be refreshed every minutes.

[fix] ensure that targets are regenerated every run

---

.travis.yml

Don't `docker pull ubuntu:bionic` — Besides this being dead code, it
causes the build to fail as per the Docker Hub rate limits

[fix] Docker Hub is dead, part deux

---

ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner

- Ensure that the `new-wp-site` script is on the runner image
- Add missing `pwgen` dependency

[fix] make new-wp-site work on awx-runner

---

docker/mgmt/new-wp-site.sh

Dans le script new-wp-site, la condition permettant de déterminer si la commande `wp core install` doit être exécutée ou non avait un problème.
Soit un nouveau site à installer, nous souhaitons donc que la commande `wp core install` se lance.
La commande ne va donc pas se lancer.
En cherchant les possibilités offertes par wp-cli, je suis tombé la dessus:
https://developer.wordpress.org/cli/commands/core/is-installed/
C'est mieux !

[fix] Fix 'wp core install' condition

---

docker/wp-base/Dockerfile

As the version-check url is giving the latest WP version

Change the API url to get the list of WP releases

---

Makefile
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-openshift-namespace/tasks/images.yml
ansible/roles/wordpress-openshift-namespace/vars/secrets-wwp-test.yml
ansible/roles/wordpress-openshift-namespace/vars/secrets-wwp.yml
docker/mgmt/Dockerfile
docker/wp-base/Dockerfile
docker/wp-base/install-plugins-and-themes.py

This pull request goes with https://github.com/epfl-si/wp-dev/pull/55
We suffer from occasional build failures because of a BadZipFile error caused by wp-manager.epfl.ch truncating the downloads (for reasons yet unknown). To remediate this, we set up a new bucket on s3.epfl.ch and put our purchased software assets there (for the time being, the list consists of the wp-media-folder and wpforms plugins).
- `install-plugins-and-themes.py` now interpets s3:// URLS in `from: ` lines of plugins.py, provided one passes the `--s3-endpoint-url`, `--s3-bucket`, `--s3-key-id` and `--s3-secret` flags to it
- For repeatable builds (also in the “past” direction), plugins.yml points to a specific release of each purchased asset by name (as opposed to the wp-manager-era practice of using a constant name …

[feature] Install purchased assets from S3

---

ansible/roles/wordpress-instance/vars/backup-vars.yml
ansible/roles/wordpress-instance/vars/wipe-vars.yml
ansible/roles/wordpress-openshift-namespace/tasks/monitoring.yml
ansible/roles/wordpress-openshift-namespace/templates/prometheus-config.yml
ansible/roles/wordpress-openshift-namespace/vars/monitoring-vars.yml

The cron job that tallies disk usage is stalling; see e.g. https://pub-os-exopge.epfl.ch/console/project/wwp/browse/pods/srv-disk-usage-report-1609898700-6bj2g?tab=details because it incorrectly tries to phone http://pushgateway:9091/
The pushgateway for things that happen in wwp is reachable at
http://pushgateway.wwp-infra:9091/, whereas the pushgateway for e.g.
the wwp-test namespace is at http://pushgateway.wwp-test:9091/
- Refactor this computation as new variables
`monitoring_pushgateway_namespace` and `monitoring_pushgateway_url`
- Use these variables throughout

[fix] Pushgateway address for the disk-usage job

---

docker/mgmt/new-wp-site.sh

Add the `--debug` param to `new-wp-site.sh`, in order to add debugging options in `wp-config.php`.
See https://wordpress.org/support/article/debugging-in-wordpress/

[feature] option to enable debug in wp-config.php

---

ansible/roles/wordpress-openshift-namespace/tasks/images.yml
ansible/roles/wordpress-openshift-namespace/tasks/main.yml

This replaces the series of `oc tag` commands that was only available as [old-school documentation](https://confluence.epfl.ch:8443/pages/viewpage.action?pageId=151912818&version=78)

[feature] `wpsible -t images.promote`

---

docker/wp-base/Dockerfile

This ought to fix the AWX failures such as https://awx-wwp.epfl.ch/#/jobs/playbook/1907

[fix] Make PHP composer symlinks relative and hence, copiable

---

ansible/roles/wordpress-instance/defaults/main/plugin-s3-vars.yml
ansible/roles/wordpress-openshift-namespace/vars/secrets-wwp.yml

- Cleaner than putting it into secrets-wwp.yml
- Still won't be used anywhere, still required for macro-expansion to work in plugins.yml

[fix] Make `build.s3_assets.bucket_name` a `default` of `roles/wordpress-instance`

---

ansible/roles/awx-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/backup.yml
ansible/roles/wordpress-instance/vars/backup-vars.yml

- Data flow was broken for the `monitoring_pushgateway_url` variable (missing include_vars + bad computation)
- Despite this, backups were working by mistake since last change around end of June, because they were operating out of an outdated Git clone

[fix] Backup Ansible tasks and variable data flows

---

ansible/roles/wordpress-openshift-namespace/tasks/main.yml
ansible/roles/wordpress-openshift-namespace/tasks/monitoring.yml

- Implement `wpsible -t monitoring.prometheus`
- Fix “Prometheus StatefulSet” task failing because of an Ansible+JSON SNAFU

[Fix] Prometheus execution in WordPress OpenShift platform

---

VARS.md
ansible/inventory/prod/group_vars/awx_instances_prod
ansible/inventory/test/group_vars/awx_instances_test
ansible/roles/awx-instance/tasks/main.yml

This prevents the operator from breaking backups when they deploy from a feature branch, and thereafter delete it (e.g. when the feature branch gets merged).
- New inventory variable `awx_is_production`, works like `openshift_is_production`
- If `awx_is_production` is set, then always use the `master` branch, except if overridden by a command-line variable
- Document that variable

[fix] Prevent naïve operator from setting a weird branch on AWX

---

ansible/roles/wordpress-instance/tasks/backup.yml
ansible/roles/wordpress-instance/vars/backup-vars.yml

Compute the required `mysqldump` command out of `wp config list
--format=json | jq`, rather than trusting wp-cli anymore.

[fix] Work around https://github.com/wp-cli/db-command/issues/195

---

ansible/roles/wordpress-instance/vars/backup-vars.yml

Continued from #443 
Bend over backwards to support jq 1.5 as per
https://stackoverflow.com/questions/51757559/jq-from-entries-function-works-with-key-but-not-name,
and also because the base `ansible-runner` image, itself based on
RedHat something-something, doesn't have jq 1.6

[fix] Bend over backwards to support jq 1.5

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Reverts epfl-si/wp-ops#447, as it was  a temp fix. Waiting for find-my-blocks to release a new version

Revert "Fix find my blocks not being available at the moment"

---

ansible/roles/awx-instance/tasks/k8s-builds.yml
ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner
ansible/roles/awx-instance/vars/k8s-vars.yml

Ansible runs on AWX have started failing because the `new-wp-site` requires Perl, which the last build of `wp-ansible-runner` doesn't have. Not exactly sure why we started noticing only this week, but here we are.
- Put Perl back
- Fix some compatibility issues with modern [`ansible-module-openshift`](https://github.com/epfl-si/ansible-module-openshift/) in the configuration-as-code for builds
- Ensure that `curl`ing a 404'd page causes the script to fail cleanly, which would have saved me a bit of a [wild goose chase](https://github.com/epfl-si/ansible-module-openshift/commit/4f3cc06a49755c906e1f6b8116621c3b7db45352) during the root cause analysis of this here PR.

[fix] wp-ansible-runner: add Perl back

---

ansible/roles/wordpress-instance/tasks/plugins.yml

- Forked https://github.com/epfl-si/wordpress.plugin.tequila from the epfl-sti depot (was already done for the other one)
- Force-pushed `master` branch in both

[fix] Use `accred` and `tequila` plugins from https://github.com/epfl-si

---

ansible/wpsible

https://github.com/ansible/ansible/issues/74725 is fatal to us, since we do need e.g. the `| int` filter to work.
- Use Ansible version 3.4.0

[fix] Move away from Ansible 2.9.6

---

ansible/roles/awx-instance/tasks/k8s-builds.yml
ansible/roles/awx-instance/tasks/k8s.yml
ansible/roles/awx-instance/tasks/pushgateway.yml
ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner
ansible/roles/awx-instance/vars/k8s-vars.yml
ansible/roles/wordpress-openshift-namespace/tasks/monitoring.yml
ansible/roles/wordpress-openshift-namespace/tasks/varnish.yml
ansible/roles/wordpress-openshift-namespace/templates/prometheus-config.yml
ansible/roles/wordpress-openshift-namespace/vars/monitoring-vars.yml
ansible/roles/wordpress-openshift-namespace/vars/varnish-vars.yml
docker/logrotate/Dockerfile
docker/varnish/Dockerfile

- Pull as many images as we can from either quay.io or public.ecr.aws
- Mirror the remaining ones
- Fix other things that prevented [prometheus-wwp](https://prometheus-wwp.epfl.ch/graph) from starting up

[fix] Avoid `ImagePullBackoff`s caused by Docker Hub's rate limit policy

---

ansible/inventory/wordpress-instances.py

After the operations in [INF-7254](https://jira.camptocamp.com/servicedesk/customer/portal/5/INF-7254) this directory doesn't exist anymore (it used to live on the test NFS share).

[fix] `/srv/dev` is no more

---

ansible/roles/wordpress-openshift-namespace/tasks/images.yml

As in the [documentation](https://docs.openshift.com/enterprise/3.1/dev_guide/builds.html) :
> Docker builds normally reuse cached layers found on the host performing
> the build. Setting the noCache option to true forces the build to ignore
> cached layers and rerun all steps of the Dockerfile.

[fix] do not use cache when building wp-base

---

.travis.yml
ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/wipe.yml
ansible/roles/wordpress-instance/vars/wipe-vars.yml
docker/collectd/Dockerfile

- Remove only the `# BEGIN WordPress` … `# END WordPress` section in `.htaccess` at `-t wp.wipe` time
- Afterwards, delete `.htaccess` only if devoid of anything non-commenty
- Option (left undocumented on purpose) to cause `-t wp.wipe` to skip backups
- Fix other bugs that prevented `-t wp.wipe` from working at all

[fix] `-t wp.wipe`: Keep relevant bits of `.htaccess` around

---

ansible/roles/wordpress-openshift-namespace/tasks/images.yml

Since `httpd` is a multi-stage build, no `FROM` rewriting takes place; in order to avoid building from a stale cache (i.e. out of a `wp-base` image that got pulled earlier), we need `forcePull: true` on this build.

[fix] (Multi-)build on bad cache

---

ansible/roles/wordpress-instance/tasks/plugins.yml

EPFL Social Graph must use plugin is now splitted from `EPFL_functions.php`, it needs to be installed.

[feature] EPFL Social Graph

---

docker/wp-base/Dockerfile

Refrain from changing it to latest LTS, as per @jdelasoie's remark that [as of late 2021](https://github.com/WordPress/gutenberg/commits/trunk/.nvmrc), Node 14 is still the version that the WordPress team recommends.

[refactor] Hermetic build of React / Gutenberg parts

---

ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner

It looks like RedHat stopped providing it as part of the upstream image (quay.io/ansible/ansible-runner:latest) for some reason.

[fix] Ensure the `oc` binary goes into the wp-ansible-runner image

---

docker/httpd/php.ini

As per https://go.epfl.ch/INC0468760, 12-factor with environment variables doesn't really play well with that 20th-century style function.
- Yes, there are legitimate use cases in unmanaged plug-ins. Too bad.

[fix] Disable the `phpinfo()` function

---

ansible/roles/wordpress-openshift-namespace/tasks/monitoring.yml
ansible/roles/wordpress-openshift-namespace/vars/monitoring-vars.yml

[Rumor has it on the Internets](https://gitlab.com/gitlab-org/gitlab/-/issues/352551#note_839508159) that the new metadata format that quay.io likes to use, is incompatible with older Dockerd's such as the one that runs on OpenShift 3.11.
As a result, [our monitoring](https://prometheus-wwp.epfl.ch/) has been firing on three cylinders for a month now.
- Fall back to using an image from docker.io
- Must mirror it first of course

[fix] `ImagePullBackoff` that has been going on for a month

---

ansible/wpsible

A future version of the Ansible suitcase will change the default value for EYAML to not install it. Same might happen later with Keybase.

[compatibility] Affirmatively require Keybase and EYAML

---

ansible/roles/awx-instance/templates/Dockerfile.wp-ansible-runner

- It just broke a manual AWX run, perhaps on account of `/tmp/wordpress_plugin-cache` not existing
- It is a dead-end prototyping idea, which even if it worked, wouldn't advance our goal (which was to run Ansible continuously every 30 minutes Puppet-style on each site, which is just not a reasonable use of our compute resources)

[unfeature] Disable cache “optimization”

---

docker/wp-base/Dockerfile
docker/wp-base/install-plugins-and-themes.py

- Added the --wp-version paramaters to install-plugins-and-themes.py
- Should be compatible with Ansible, thanks to this change 002a61f14eed9cdeba339e061c24738aa47b4403
Example of usage :
```
- name: Polylang for WP 5.5 plugin
when: wp_current_version < 5.6
wordpress_plugin:
name: polylang
state:
- symlinked
- active
from: https://downloads.wordpress.org/plugin/polylang.2.9.2.zip
- name: Polylang plugin
when: wp_current_version >= 5.6
wordpress_plugin:
name: polylang
state:
- symlinked
- active
from: wordpress.org/plugins
```

Allow to specify a conditional plugin install, based on the current wp version

---

docker/wp-base/install-plugins-and-themes.py

As to reduce size of the plugins/themes folders when they are cloned from github

[optimize] Single branch checkout instead of the whole git branches

---

ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py
ansible/roles/wordpress-instance/tasks/plugins.yml
docker/wp-base/install-plugins-and-themes.py

I had to go this path because when we use a direct branch url (like github.com/epfl-si/wp-gutenberg/tree/update/5.9) for a checkout, the script has no way to differentiate if it is a branch to checkout or a subfolder/file to get (see https://github.com/epfl-si/wp-ops/blob/bb25026b30b4dc804a6bb1271bb28bece060fa67/ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py#L141)

Add a way to select a specific branch when getting a Plugin from Github

---

ansible/roles/wordpress-openshift-namespace/tasks/continuous-integration.yml
ansible/roles/wordpress-openshift-namespace/tasks/main.yml
docker/jenkins/Dockerfile
docker/jenkins/configuration-as-code.yml
docker/jenkins/epfl-plugins.txt

- Overhaul the Jenkins setup that Camptocamp did for us. Instead of mounting /var/lib/jenkins on NFS whole (and thus making it all persistent, including the configuration, the set of plug-ins etc.), only mount /var/lib/jenkins/jobs and /var/lib/jenkins/logs
- Deploy and use the [configuration-as-code plugin](https://plugins.jenkins.io/configuration-as-code/)
- ... And that's it — As it turns out, OpenShift's default configuration for Jenkins gets a lot of things right without having to touch (including access control).
Also:
- It appears that the JNLP port moved from 5000 to 50000 for some reason. Fix that.
- Change Ansible code to rebuild Jenkins images whenever the `BuildConfig` / `ImageStream` objects change, and/or when explicitly told (using `wpsible -t ci.rebuild`).

[feature] Configuration-as-code for Jenkins + capability to send emails

---

ansible/wpsible

This fixes a crash when using the `version_compare` operator (itself caused by https://github.com/ansible/ansible/issues/76490)

[upgrade] Ansible to version 6.3.0

---

ansible/roles/wordpress-openshift-namespace/tasks/mgmt.yml

As we changed backups strategy from the NFS to S3, we need to remove the unused volumeClaim /backups.
See https://jira.camptocamp.com/servicedesk/customer/portal/5/INF-9392 for more info.

Remove backups-0 ("/backups" in mgmt) from the DeploymentConfig

---

ansible/roles/wordpress-openshift-namespace/tasks/images.yml

Not sure how this worked in the first place: did the behavior of `openshift_imagestream` allow for a more liberal kind of implicit chaining in the past? Or was that piece of the `BuildConfig` added by hand? Anyway, today we saw that the assumption that Jenkins makes (that launching a `wp-base` build, will trigger the others automatically) no longer holds.
Fix that by having explicit `triggers:` stanzas in the configuration-as-code (instead of relying on whatever aforementioned technique we used for triggers previously

[fix] Explicit triggers for images that depend (directly or indirectly) on `wp-base`

---

ansible/roles/wordpress-instance/tasks/plugins.yml

This commit get ride of all the maneuvering in order handle 2 versions of WPForms. Let's use the latest version available right now (i.e.  1.8.0.2) and the latest version of wpforms-epfl-payonline.

[feature] Latest WPForms

---

ansible/wpsible

Now with the `--username` set to `$USER`. This allows the user to enter its password instead of login to OpenShift to fetch its token.

[fix] oc login

---

docker/logrotate/Dockerfile
docker/varnish/Dockerfile

As per https://www.debian.org/releases/stretch/index.en.html it looks like Debian Stretch is dead.

[upgrade] Debian images to `bullseye`

---

ansible/roles/wordpress-instance/tasks/backup.yml
ansible/roles/wordpress-instance/vars/backup-vars.yml

Right now, and for reasons yet unknown, the “Backup” task for `www__labs__dcsl` takes *days* and we get an alert for that site.
Given that the last log line at https://awx-wwp-infra.epfl.ch/#/jobs/playbook/5288 is currently dated 2023-09-27T01:16:56.110490Z; while the task headline (“Backup”) (i.e. the event `playbook_on_task_start`, which is the first item in https://awx-wwp-infra.epfl.ch/api/v2/jobs/5288/job_events/?counter__gte=8017&counter__lte=8062&order_by=start_line&page_size=200 ) is dated 2023-09-26T19:28:51.624270Z; 6h ought to be enough, but since the actual deadline is 24h (i.e. before the next crontab starts) we can add 2 hours of slack.

[fix] Time out the backup step after 8h

---

ansible/roles/wordpress-instance/action_plugins/wordpress_action_module.py

- Move file concerns (as opposed to wp-cli concerns, whether related to the database or `wp <plugin|theme> install`) into a separate class
- Do something smart when changing a file from `symlinked` to `installed`; that is, copy it out of `/wp` using Ansible's good old [`copy` module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html)
- Leave open the possibility for smart subclasses to do things better, i.e. if e.g. `wp plugin install` runs before the Ansible actions changed by this PR, they would find the files already in the expected state and do nothing.

[fix] Refactor and fix the logic that deals with `symlinked` vs. `installed` files

---

ansible/roles/wordpress-instance/tasks/plugins.yml

Set version 7.5.0 of EWWW Image Optimizer plugin to stay compatible with WP 6.1

fix: Set a fixed version of ewww, the last known to work with WP 6.1

---

ansible/roles/wordpress-instance/vars/plugin-vars.yml

... not sure how this could possibly work before ‽

[fix] We don't want a list in the `plugin_restauration_api_password` structure

---

ansible/roles/wordpress-instance/action_plugins/wordpress_polylang_language.py

Apparently, `wp pll lang list --fields=mo_id` no longer works — Might be related to Polylang 3.4 [dropping support for it](https://polylang.pro/polylang-3-4-eases-the-translation-of-custom-tables/) (under § “Some public properties are removed”)

[fix] crash in `_get_polylang_languages`

---

docker/wp-base/Dockerfile

From [the savoury1 PPA](https://launchpad.net/~savoury1), we only require curl; however it appears to also offer git, and to do so differently between processor architectures ☹.

[fix] build on M1 processors

---

ansible/roles/wordpress-openshift-namespace/tasks/main.yml
ansible/roles/wordpress-openshift-namespace/tasks/menu-api.yml

Use
- `oc get cronjob -n wwp -o wide` to get the cronjob list
- `oc get pods -n wwp -o wide | grep menu-api-refresh` to get the name  of the pod of the last run
- `oc logs menu-api-refresh-cron-1234567890-abcd3 -n wwp` to have the  logs

[feature] CronJob to refresh the Menu's API's cache

---

ansible/roles/wordpress-instance/tasks/plugins.yml

As in version 4.*, the route `blocks` that we pull requested  (https://github.com/morganhvidt/find-my-blocks/commit/0e7e68414c59d9a5bb3eed74d87b542b80c3c776)  is no longer avalaible. Before changing everything, this is an attempt  to pin down the version in order to make it work.

[fix] Pin down the version of the Find My Blocks plugin

---

ansible/roles/wordpress-instance/tasks/backup.yml

Investigation (e.g. in `s3://svc0041-b80382f4fba20c6c1d9dc1bebefc5583/backup/wordpresses/www__research__domains__transportation_center/sql`) reveals that SQL “backups” on a `.htaccess`-only site used to work just fine (before https://github.com/epfl-si/wp-ops/pull/558 that is). We see snippets like this being “backed up,”
```
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help
```
indicating that `mysqldump` used to return success (0 exit code) when called with no arguments (as a result of `wp config list --format=json | jq` in `backup_db_to_stdout_command` returning nothing). (As an aside, this wasn't caught by our `set -e` nor `set -o …

[fix] Back up sites without a wp-config.php

---

.travis.yml
docker/wp-base/install-plugins-and-themes.py

Some of the WordPress plugins that we use are hosted on EPFL's S3-compatible on-premise server, for various reasons (e.g. the plugin was discontinued upstream, or it was paid-for and its source code should not be made public). For cases in which S3 access and/or credentials are unavailable (e.g. the Travis build), we used to have a blacklist mechanism with `install-plugins-and-themes.py`'s `--exclude` flag.
This PR makes it so that omitting the `--s3-endpoint-url` flag  implicitly `--exclude`s any and all plugins hosted on S3.

[feature] `install-plugins-and-themes.py`: auto-skip S3 plugins

---

ansible/roles/awx-instance/tasks/awx-objects.yml
ansible/roles/awx-instance/vars/main.yml

Symptom:
Root cause: the job times out after 4h (AWX's default).
Before:
After this PR:

[fix] Slice production backup job 6-fold

---

docker/httpd/Dockerfile
docker/wp-base/Dockerfile

This is take 2 of #553 which was [reverted](https://github.com/epfl-si/wp-ops/pull/553). This time around, all the tweaks are guarded so that they cannot possibly interfere with the `x86_64` architecture.
There are various not-so-subtle variations on `ppa:savoury1/backports` between the `x86_64` and `aarch64` architecture; for instance, it only carries `git` for the former... yet it has `git-man` for both  🤦

[fix] the build on M1

---

kopf-operator/WordPressSite-crd.yaml

The previous regex wanted a full word of 3 characters, which wasn't  always convenient.

[fix] Minimum of 3 caracters

---

ansible/roles/wordpress-instance/tasks/main.yml
ansible/roles/wordpress-instance/tasks/plugins.yml
ansible/roles/wordpress-instance/vars/plugin-vars.yml

The Very Simple Meta Description plugin allows users to set meta-data  for the site (`<meta name="description"...`). One of its options allow  to use pages and posts excerpts as meta description, but this option is  off by default.
This commit:
- Set the `vsmd-setting-2` to yes in the wp-options table (the setting  we are interested in)
- Add the tag `-t wp.plugins.vsmd` to wpsible
- Sort the tags for the plugins in alphabetical order
Also, see [WEBEVOL-252](https://epfl-webvolution.atlassian.net/browse/WEBEVOL-252).

[feature] Set option for VSMD

---

docker/nginx/Dockerfile
docker/nginx/php.ini

Dear PHP, please be hereby informed that the kernel has a `realpath()` cache too. Which actually does work i.e. it is kept coherent when Kubernetes updates its Rube Goldberg symlinks.

[fix] WPN-79

---

ansible/roles/wordpress-openshift-namespace/tasks/buildconfig-prerequisites.yml

I admit I didn't read https://access.redhat.com/solutions/7098226 all the way through. I stopped at the “Resolution” § and translated it into Ansible.

[workaround] In OpenShift 4.15, we need `imagePuilSecrets` as well

---

ansible/roles/rke2-cluster/tasks/main.yml
ansible/roles/rke2-cluster/tasks/nginx.yml

- `wpn-*` → `wp-*`
- Remove typeful suffixes e.g. `wp[n]-nginx-service` → `wp-nginx`

[refactor] Kubernetes object names for serving

---

ansible/roles/wordpress-namespace/tasks/main.yml
ansible/roles/wordpress-namespace/tasks/nginx.yml

Fixes [WPN-218](https://go.epfl.ch/WPN-218) in part (the other part being [already in `epfl-si/wp-operator`](https://github.com/epfl-si/wp-operator/commit/7fe22f63588abcb981f7a16f06901f1332b0a3a7))
On an EPFL “official” OpenShift instance with namespace-as-a-service (that we don't have cluster-admin on), only the [OLM controller](https://github.com/epfl-si/wp-operator/tree/main/olm) can set up RBAC on our behalf. On the other hand, Rancher doesn't have OLM, and thus we need to manage RBAC through Ansible there.
- Introduce `_rbac_managed` Boolean variable to discern these case
- Pepper `ansible/roles/wordpress-namespace/tasks/nginx.yml` with `when: _rbac_managed` constructs for all things RBAC
[WPN-218]: https://erpdev.atlassian.net/browse/WPN-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …

[fix] Do the RBAC on RKE2 namespaces only

---

ansible/roles/wordpress-namespace/tasks/storage.yml

- Downplay the actual storage use, so as not to upset quota computations 😉 (the real metering of this resource happens in the NAS, rather than in OpenShift)
- Have the PV point to the PVC, rather than the other way round. This way, it is not possible to “steal” our PV between the time our ticket is acted upon, and the time we get around to running `wpsible -t wp.storage` again
- Set the shared `storageClassName` to the empty string

[fix] Do our PVs / PVCs “the ITOP-SDDC way”

---

ansible/roles/wordpress-namespace/tasks/mariadb.yml
ansible/roles/wordpress-namespace/tasks/nginx.yml

[feature] Define the StorageClass (no more `mariadb-min`)
- Without specifying it, the default StorageClass is used: we need to use "our" StorageClass defined with the `NfsSubdirProvisioner`.
- Use a variable for the `kind: MariaDB` object's name
- Add a `mariadb-vars.yaml` for MariaDB specific vars

[feature] Define the StorageClass (no more `mariadb-min`)

---

ansible/roles/wordpress-instance/tasks/break-wp-admin-symlink.yml
ansible/roles/wordpress-instance/tasks/main.yml

**Break symlink wp-admin and backup on s3**
For migration to s4, remove symlink wp-admin to avoid users to edit on wp-admin, and backup afterwards. 
Tags:
- `wp.break-wp-admin-symlink` → remove symlink wp-admin
- `wp.mig_os4` → remove symlink wp-admin and run backups on s3
Example: remove symlink wp-admin of [hostname] and backups on s3
`./wpsible -l [hostname] -t wp.mig_os4 `

[feature](WPN-271) Remove wp-admin's symlink and run backups

---

ansible/roles/wordpress-namespace/tasks/mariadb.yml
ansible/roles/wordpress-namespace/vars/mariadb-vars.yml

This will deploy the number of MariaDBs (servers) defined by the
variable `number_of_mariadb` in the `svc0041p-wordpress` namespace, but
only 2 in other namespaces. This is hard-coded in the `with_sequence`
Ansible parameter.
This also create the Backups objects, which are set to be ran at
the hour defined by identifier used for the naming of the MariaDB.
`mariadb-01`'s backups will be ran at 1, `mariadb-02`'s backups will be
ran at 2, etc. This is a temporary and very basic way to unsure that the
backups will not use all resources at once.

[feature] Multiple MariaDBs

---

ansible/roles/wordpress-namespace/tasks/nginx.yml
docker/wp-base/install-wordpress.sh

Attention everyone: just like in `wp-ops` itself, changes to the mu-plugins must now be merged into WPN to appear in OpenShift 4.

[feature] Use newly-created `WPN` branch of `epfl-si/wp-mu-plugins`

---

ansible/roles/wordpress-namespace/tasks/nginx.yml

https://erpdev.atlassian.net/browse/WPN-239
Create pod anti-affinity rules to (at a minimum) prevent both pods from running on the same node.
Additionally, enforce that they run in different data centers.

[feature](WPN-239) Add wp-nginx pods affinity rules

---

docker/wp-base/install-wordpress.sh

I carefully cut the [`WPN` branch in `wp-theme-2018`](https://github.com/epfl-si/wp-theme-2018/tree/WPN) so that there is no difference with the current content of `/wp/6/wp-content/themes/wp-theme-2018/` of version  2025-011 [in Quay](https://quay-its.epfl.ch/repository/svc0041/wp-nginx?tab=tags).

[fix] Pin theme to last-known working version in prod

---

ansible/roles/wordpress-namespace/tasks/nginx.yml

https://erpdev.atlassian.net/browse/WPN-240
Create a PodDisruptionBudget to prevent OpenShift from scheduling its update by terminating both pods at the same time.

[feature](WPN-240) Add PodDisruptionBudget for wp-nginx

---

ansible/roles/wordpress-namespace/tasks/nginx.yml
docker/wordpress-php/nginx-entrypoint.php

- This is not going to work on Kubernetes anyway
- Although correlation is not causation, I found some [interesting evidence](https://grafana-prod-route-grafana-prod.apps.ocpitsp0001.xaas.epfl.ch/goto/6ZfSxZcNR?orgId=1) that the self-upgrade attempts might have something to do with our serving infrastructure buckling every night around 22:25PM CEST for the last 9 days:

[fix] Block auto-updates and other self-modifying PHP code

---

ansible/roles/wordpress-namespace/tasks/menu-api.yml

Menu-api needs a service account to be able to enumerate `WordpressSite`s from k8s

[fix] create menu api service account

---

ansible/roles/wordpress-namespace/tasks/nginx.yml

- Bump up CPU for the `php-fpm-exporter` in production
- Up serving CPU in test from 20m to 200m

[fix] Tune up CPU allocation in test and production

---

ansible/roles/wordpress-namespace/tasks/main.yml
ansible/roles/wordpress-namespace/tasks/nginx.yml
ansible/roles/wordpress-namespace/tasks/storage.yml
ansible/roles/wordpress-namespace/vars/storage-vars.yml

The PVCs and XaaS-side NAS subdirectories were renamed around January, 20th (for test) or 21th (for prod), but apparently these changes never made it to the configuration-as-code. Neither did the `NfsSubdirExternalProvisioner` objects that we need for our NFS-provisioned storage scheme.
While we are in there:
- Tune the CPU reservation in said `NfsSubdirExternalProvisioner`s, freeing almost one full CPU in our tiny test namespace
- Reorder `-t wp.storage` before `-t wp.mariadb`, now that the latter depends on the former

[fix] some bit rot in persistence configuration-as-code

---

ansible/roles/wordpress-namespace/tasks/main.yml
ansible/roles/wordpress-namespace/tasks/monitoring.yml
ansible/roles/wordpress-namespace/vars/monitoring-secrets.yml

**Description**
https://erpdev.atlassian.net/browse/WPN-163
> Objectif : être prévenu au moment où (et idéalement, quelque temps avant que) la plate-forme OpenShift 4 n’est plus capable d’assurer les services dont nous dépendons.
> * Deployment qui n’a pas le nombre de pods demandé
> * Monitoring inaccessible (mesuré avec up)

[feature](WPN-163) Add basic internal alerting

---

ansible/roles/wordpress-namespace/tasks/monitoring.yml

> https://erpdev.atlassian.net/browse/WPN-326
> 
> The graphs of https://grafana-prod-route-grafana-prod.apps.ocpitsp0001.xaas.epfl.ch/goto/w0q-uq5Hg?orgId=1 (from the third onwards) are all abnormal if they are not empty.
> 
> Add alerts on:
> 
>      phpfpm_process_request_duration > 30 * 1000 * 1000
> 
>     rate(nginx_http_requests_total{status = 499}) > 0
> 
>         And also : rate(nginx_http_requests_total{status = 500}) > 0 ; rate(nginx_http_requests_total{status = 504}) > 0 
> 
> All this for a fairly short duration; say 2 minutes to start with.
> 
> Alerts are grouped by instance.

[feature](WPN-326) Add alerts on Nginx errors and PHP high process request duration

---

ansible/roles/wordpress-namespace/tasks/main.yml

- `-t wp` pushes the entire role
- `-t wp.web` pushes everything that is in the critical path of Web requests: nginx, php-fpm and menu-api
- `-t wp.menus` pushes only menu-api
- Likewise, `-t wp.monitoring` pushes both Prometheus and Grafana things, whereas `-t wp.grafana` concerns itself with Grafana only
- Keep old (unstructured) tags

[feature] Rework tag scheme in `wordpress-namespace` role

---

ansible/roles/wordpress-namespace/templates/grafana/nginx.json

- "Nginx” is not a thing
- We don't want to mention lua, which is an internal detail (except for the nginx-lua-prometheus errors)

[fix] names in nginx dashboards

---

ansible/roles/wordpress-namespace/tasks/monitoring.yml

**Description**
Do not print the `pod` and `instance` labels for this alert.

[fix] MariaDB alert message

---

docker/wordpress-nginx/nginx.tmpl
docker/wordpress-php/Dockerfile

This is to confirm that the daily 22:22 outage of
https://go.epfl.ch/WPN-318 fame, is caused by a surge of wp-cron.php
traffic (as the evidence in CloudFlare currently suggests):

[investigate] Disable wp-cron.php on a trial basis

---

ansible/roles/wordpress-namespace/templates/grafana/nginx.json

**Description**
Removed repetitive panels per pod in the nginx Grafana dashboard, and consolidated traces based on the selected pod in variables.
For reviewers, see the demo [here](https://grafana-prod-route-grafana-prod.apps.ocpitsp0001.xaas.epfl.ch/d/b_lN9SZWA/nginx-next-test-olivier?orgId=1&from=now-1h&to=now&timezone=browser&var-pod=$__all&var-host=www.epfl.ch&refresh=10s).

[feature] Do not repeat panels per pod in nginx Grafana dashboard

---

ansible/roles/wordpress-namespace/tasks/monitoring.yml

Split menu api refresh alert in two: une for refreshes and one for other end point

[fix] Split menu api refresh alert

---

ansible/roles/wordpress-namespace/tasks/nginx.yml
ansible/roles/wordpress-namespace/vars/image-vars.yml

Now we can use the `nginx_deployment_images_tag` variable in `ansible/roles/wordpress-namespace/vars/image-vars.yml` to set the tag used for `wp-php` and `wp-nginx` images.

[feature] Use of a variable for `wp-nginx`'s images tag

---

ansible/playbook.yml
ansible/requirements.yml
ansible/roles/olm-catalog/tasks/buildconfig-prerequisites.yml
ansible/roles/olm-catalog/tasks/main.yml
ansible/roles/olm-catalog/vars/catalog-vars.yml
ansible/roles/quay-consumer-namespace/tasks/main.yml
ansible/roles/quay-consumer-namespace/tasks/quay-puller-robot-account.yml
ansible/roles/wordpress-namespace/tasks/menu-api.yml
ansible/roles/wordpress-namespace/tasks/nginx.yml
ansible/roles/wordpress-namespace/vars/image-vars.yml
ansible/vars/quay-secrets.yml
ansible/vars/quay-vars.yml

- New `quay-consumer-namespace` role, guarded by `-t quay`
- Download robot account tokens from the Quay API
- Create secrets out of them

[feature] `-t quay`: obtain robot account tokens, create image pull secrets

---

ansible/roles/wordpress-namespace/tasks/main.yml
ansible/roles/wordpress-namespace/tasks/redirector.yml
ansible/roles/wordpress-namespace/tasks/storage.yml
ansible/roles/wordpress-namespace/vars/image-vars.yml
docker/apache-redirector/Dockerfile
docker/apache-redirector/README.md
docker/apache-redirector/httpd.conf

This introduce a new pod "wp-redirector" that allows us to:
- Keep the same filesystem layout for subdomains
- Keep the Apache's `.htaccess` as they were in the previous infrastructure
- Mange redirection with routes pointing to this pod

[feature](WPN-343) Subdomains redirection

---

docker/wordpress-php/Dockerfile
docker/wp-base/Dockerfile
docker/wp-base/symlink-wp-versions.sh
docker/wp-base/wp-cli-config.yml
docker/wp-base/wp.sh

- Host it under `/wp/wp-cli` (as well as its packages, in the `wp package install` sense)
- Provide configuration and a shell wrapper sufficient to make
```
wp --ingress=www-labs-jaksic-lab plugin list
```
work

[feature] “cloud-native” wp-cli

---

ansible/roles/wordpress-namespace/tasks/nginx.yml
ansible/roles/wordpress-namespace/vars/image-vars.yml
docker/wordpress-nginx/Dockerfile

... a.k.a. [CVE-2025-1974](https://www.cve.org/cverecord?id=CVE-2025-1974) et al.
- Rewrite `docker/wordpress-nginx/Dockerfile` to use `bitnami/nginx-ingress-controller` (which has been patched for the CVEs pointed to by
https://www.reddit.com/r/kubernetes/comments/1jjh7am/ingressnightmare_how_to_find_potentially/), rather than `rancher/nginx-ingress-controller` which has yet to do its homework
- Make the production image `FROM` the Openresty image, copying the `/nginx-ingress-controller` statically-linked binary `--from=ingress`; rather than the other way round
- Bump all dependencies while we are there

[security] Thwart #IngressNightmare

---

ansible/inventory/prod/wordpress_namespaces.yml
ansible/inventory/test/wordpress_namespaces.yml

This makes
```
wpsible -l namespace/wordpress-test
```
work as you would expect, which the piped version wouldn't.

[fix] Shell-quote-proof inventory

---

docker/wordpress-nginx/Dockerfile

- Remove the "Welcome to OpenResty!" page ([WPN-366](https://go.epfl.ch/WPN-366))
[WPN-366]: https://erpdev.atlassian.net/browse/WPN-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[fix] Remove OpenResty default welcome page

---

ansible/roles/wordpress-namespace/tasks/monitoring.yml

- Double hyphens (`--`) becomes [em dash](https://en.wikipedia.org/wiki/Dash#Em_dash) (`―`)
- Play around with spaces to avoid too many of them

[fix] `s/--/—/g` and triple spaces

---

ansible/roles/wordpress-namespace/vars/image-vars.yml

Currently available for testing at https://wpn-test.epfl.ch/

[bump] serving images to version 2025-131

---

ansible/roles/wordpress-namespace/tasks/wp-cron.yml

(The wp-base underlying) this image contains https://github.com/epfl-si/wp-plugin-pushgateway/commit/f74542340c4c2a5ac59ab6b20410f4325ae47b12 which we want to have working ASAP.

[bump] wp-cron image to version 2025-039

---

ansible/roles/wordpress-namespace/tasks/wp-cron.yml
docker/wp-cron/wordpresses.py

As explained [here](https://datatracker.ietf.org/doc/html/rfc6902#section-4.1), for the `add` operator "If the target location specifies an object member that does exist, that member's value is replaced".
for the `replace` operator instead, [here](https://datatracker.ietf.org/doc/html/rfc6902#section-4.3), "The target location MUST exist for the operation to be successful"

[fix] Add status when it doesn't exist

---

ansible/roles/wordpress-builds/tasks/tekton.yml

We began to use `noble` instead of `jammy`, so let's be more generic in  the `FROM` image replacement.

[fix] Replace all ubuntu sources

---

docker/wp-base/Dockerfile
docker/wp-base/wp-sbom.sh

Add a script that generates a Software Bill of Materials (SBOM) in YAML format
for a WordPress serving image. It scans the specified wp-content directory for
plugins, mu-plugins, and themes, extracting their version information from the
main plugin file or style.css (for themes). Additionally, it attempts to gather
Git repository information (commit hash, branch, and repo URL) for each item, if
available.
The script is called at the `wp-base` image build and the result can be accessed
in `/wp-admin/wordpress_sbom.txt` once the image runs.

[feature] (WPN-438) SBOM of the WordPress installation

---

docker/wordpress-nginx/nginx.tmpl

This uncouples the operator from nginx by this much, making it easier to implement site-independent changes in the serving discipline (such as [moving the goods from `/wp/6` to `/wp`](https://github.com/epfl-si/wp-ops/pull/683)).
See also: https://github.com/epfl-si/wp-operator/pull/59

[refactor] Move as much nginx config as possible into the template

---

docker/wordpress-nginx/nginx.tmpl
docker/wordpress-php/nginx-entrypoint.php

Once [CHG0046598](https://go.epfl.ch/CHG0046598) is complete, we no longer need support for the legacy Ingress format.

[unscaffold] Drop support for “old-style” Ingress objects
